(function (root, factory) {
  const data = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = data;
  if (root) root.GRADE6_DIAGNOSTIC = data;
})(typeof window !== "undefined" ? window : globalThis, function () {
  "use strict";

  const sections = [
    {
      id: "listening",
      title: "Part 1｜聽力理解",
      shortTitle: "聽力",
      description: "每題可播放兩次。請只聽，不要讓孩子看到英文原句。",
    },
    {
      id: "recognition",
      title: "Part 2｜單字辨識",
      shortTitle: "辨識",
      description: "從句子或選項判斷單字意思。",
    },
    {
      id: "recall",
      title: "Part 3｜主動回想",
      shortTitle: "回想",
      description: "沒有英文選項。依句意與中文提示輸入英文。",
    },
    {
      id: "grammar",
      title: "Part 4｜文法應用",
      shortTitle: "文法",
      description: "選出能讓整句自然、正確的答案。",
    },
    {
      id: "reading",
      title: "Part 5｜閱讀理解",
      shortTitle: "閱讀",
      description: "閱讀兩篇短文，再回答問題。可以回頭查看文章。",
    },
    {
      id: "performance",
      title: "Part 6｜寫作與口說",
      shortTitle: "表達",
      description: "孩子先獨立完成，再由家長依量表選擇最接近的表現。",
    },
  ];

  const passages = [
    {
      id: "bike_story",
      title: "The Saturday Ride",
      text:
        "On Saturday morning, Mia and her brother Noah planned to ride their bikes to the riverside park. They left home early because they wanted to meet their friends at nine o’clock. Halfway there, Noah’s bike chain came off. Mia did not have the right tool, but she remembered a repair shop near the market. She walked the two bikes there while Noah called their friends. The mechanic fixed the chain in ten minutes and showed Noah how to check it. They reached the park twenty minutes late. Their friends were still waiting, and everyone was relieved. Before riding home, Noah checked the chain by himself.",
    },
    {
      id: "bottle_report",
      title: "A Better Drink Plan",
      text:
        "Class 6 wants to reduce plastic waste at school. The students surveyed 60 classmates. Forty-two students said they usually buy bottled drinks, while only eighteen carry a reusable bottle. The class discussed two plans. Plan A is to install a refill station. It costs more at first, but it may reduce the number of plastic bottles. Plan B is to add more recycling bins. It is cheaper, but it does not stop students from buying bottles. The class recommends Plan A together with a one-month “Bring Your Bottle” campaign. They will survey students again afterward to see whether the plan works.",
    },
  ];

  const questions = [
    {
      id: "L1",
      section: "listening",
      tier: "Core",
      type: "mc",
      spoken:
        "Nina usually walks to school, but today her father is driving her.",
      prompt: "How is Nina going to school today?",
      choices: ["By car.", "On foot.", "By bus.", "By bike."],
      answer: "By car.",
      word: "usually",
    },
    {
      id: "L2",
      section: "listening",
      tier: "Core",
      type: "mc",
      spoken: "Put the blue notebook between the dictionary and the lamp.",
      prompt: "Where should the blue notebook go?",
      choices: [
        "Between the dictionary and the lamp.",
        "Under the dictionary.",
        "Behind the lamp.",
        "Next to the door.",
      ],
      answer: "Between the dictionary and the lamp.",
      word: "between",
    },
    {
      id: "L3",
      section: "listening",
      tier: "Bridge",
      type: "mc",
      spoken: "Leo was reading when the lights went out.",
      prompt: "What was Leo doing?",
      choices: [
        "He was reading.",
        "He was sleeping.",
        "He was fixing the lights.",
        "He was leaving the room.",
      ],
      answer: "He was reading.",
      word: "reading",
    },
    {
      id: "L4",
      section: "listening",
      tier: "Bridge",
      type: "mc",
      spoken:
        "Maya has already finished her science report, so she can help her partner.",
      prompt: "What has Maya finished?",
      choices: [
        "Her science report.",
        "Her art project.",
        "Her partner’s homework.",
        "Her lunch.",
      ],
      answer: "Her science report.",
      word: "already",
    },
    {
      id: "L5",
      section: "listening",
      tier: "Bridge",
      type: "mc",
      spoken:
        "If the weather improves, the team will test the machine outside.",
      prompt: "What must happen before the team tests outside?",
      choices: [
        "The weather must improve.",
        "The machine must break.",
        "The team must go home.",
        "The report must disappear.",
      ],
      answer: "The weather must improve.",
      word: "improve",
    },
    {
      id: "L6",
      section: "listening",
      tier: "Extension",
      type: "mc",
      spoken:
        "The device was designed by a student who wanted to reduce food waste.",
      prompt: "Why was the device designed?",
      choices: [
        "To reduce food waste.",
        "To make food more expensive.",
        "To measure the classroom.",
        "To replace the student.",
      ],
      answer: "To reduce food waste.",
      word: "reduce",
    },

    {
      id: "V1",
      section: "recognition",
      tier: "Core",
      type: "mc",
      prompt: "A visitor is waiting at the front desk. What is a “visitor”?",
      choices: ["訪客", "組長", "店員", "鄰居"],
      answer: "訪客",
      word: "visitor",
    },
    {
      id: "V2",
      section: "recognition",
      tier: "Core",
      type: "mc",
      prompt:
        "The library is opposite the station. Where is the library?",
      choices: ["在車站對面", "在車站裡面", "在車站後方很遠處", "在車站樓上"],
      answer: "在車站對面",
      word: "opposite",
    },
    {
      id: "V3",
      section: "recognition",
      tier: "Core",
      type: "mc",
      prompt: "Which meaning fits “route”?",
      choices: ["路線", "結果", "規則", "高度"],
      answer: "路線",
      word: "route",
    },
    {
      id: "V4",
      section: "recognition",
      tier: "Bridge",
      type: "mc",
      prompt:
        "The photo gives us evidence that the animal was here. What does “evidence” mean?",
      choices: ["證據", "意見", "危險", "設備"],
      answer: "證據",
      word: "evidence",
    },
    {
      id: "V5",
      section: "recognition",
      tier: "Bridge",
      type: "mc",
      prompt: "A reliable source usually gives information we can ____.",
      choices: ["trust", "hide", "break", "forget"],
      answer: "trust",
      word: "reliable",
    },
    {
      id: "V6",
      section: "recognition",
      tier: "Bridge",
      type: "mc",
      prompt: "“Approximately 100 students” means ____.",
      choices: [
        "about 100 students",
        "exactly 100 students",
        "fewer than 10 students",
        "more than 1,000 students",
      ],
      answer: "about 100 students",
      word: "approximately",
    },
    {
      id: "V7",
      section: "recognition",
      tier: "Extension",
      type: "mc",
      prompt: "If you persuade someone, you ____.",
      choices: [
        "make them agree by giving reasons",
        "copy everything they write",
        "measure how tall they are",
        "ask them to remain silent",
      ],
      answer: "make them agree by giving reasons",
      word: "persuade",
    },
    {
      id: "V8",
      section: "recognition",
      tier: "Extension",
      type: "mc",
      prompt: "A misleading title may make readers ____.",
      choices: [
        "believe something that is not true",
        "understand every detail correctly",
        "speak more clearly",
        "finish the article faster",
      ],
      answer: "believe something that is not true",
      word: "misleading",
    },

    {
      id: "A1",
      section: "recall",
      tier: "Core",
      type: "input",
      prompt: "Please be ___ with the glass.（小心的）",
      answer: "careful",
      accepted: ["careful"],
      word: "careful",
    },
    {
      id: "A2",
      section: "recall",
      tier: "Core",
      type: "input",
      prompt: "This is the shortest ___ to the museum.（路線）",
      answer: "route",
      accepted: ["route"],
      word: "route",
    },
    {
      id: "A3",
      section: "recall",
      tier: "Core",
      type: "input",
      prompt: "The lights went out ___.（突然）",
      answer: "suddenly",
      accepted: ["suddenly"],
      word: "suddenly",
    },
    {
      id: "A4",
      section: "recall",
      tier: "Bridge",
      type: "input",
      prompt: "Practice can help you ___ your writing.（改善）",
      answer: "improve",
      accepted: ["improve"],
      word: "improve",
    },
    {
      id: "A5",
      section: "recall",
      tier: "Bridge",
      type: "input",
      prompt: "Let’s ___ the two plans before we choose.（比較）",
      answer: "compare",
      accepted: ["compare"],
      word: "compare",
    },
    {
      id: "A6",
      section: "recall",
      tier: "Bridge",
      type: "input",
      prompt: "We should protect the ___.（環境）",
      answer: "environment",
      accepted: ["environment"],
      word: "environment",
    },
    {
      id: "A7",
      section: "recall",
      tier: "Extension",
      type: "input",
      prompt: "The photo is useful ___ for our report.（證據）",
      answer: "evidence",
      accepted: ["evidence"],
      word: "evidence",
    },
    {
      id: "A8",
      section: "recall",
      tier: "Extension",
      type: "input",
      prompt: "At the end of the report, write a short ___.（結論）",
      answer: "conclusion",
      accepted: ["conclusion"],
      word: "conclusion",
    },

    {
      id: "G1",
      section: "grammar",
      tier: "Core",
      type: "mc",
      prompt: "Lena ___ my partner.",
      choices: ["is", "are", "am", "be"],
      answer: "is",
      grammar: "be",
    },
    {
      id: "G2",
      section: "grammar",
      tier: "Core",
      type: "mc",
      prompt: "There ___ two notebooks on the desk.",
      choices: ["are", "is", "has", "be"],
      answer: "are",
      grammar: "there-is-are",
    },
    {
      id: "G3",
      section: "grammar",
      tier: "Core",
      type: "mc",
      prompt: "___ Evan play basketball after school?",
      choices: ["Does", "Do", "Is", "Has"],
      answer: "Does",
      grammar: "present-simple-question",
    },
    {
      id: "G4",
      section: "grammar",
      tier: "Core",
      type: "mc",
      prompt: "Look! The dog ___ under the table.",
      choices: ["is hiding", "hides", "hid", "has hide"],
      answer: "is hiding",
      grammar: "present-progressive",
    },
    {
      id: "G5",
      section: "grammar",
      tier: "Core",
      type: "mc",
      prompt: "Yesterday, we ___ the old station.",
      choices: ["visited", "visit", "are visiting", "have visit"],
      answer: "visited",
      grammar: "past-simple",
    },
    {
      id: "G6",
      section: "grammar",
      tier: "Bridge",
      type: "mc",
      prompt: "While I was drawing, my brother ___ to music.",
      choices: ["was listening", "listens", "has listened", "will listen"],
      answer: "was listening",
      grammar: "past-progressive",
    },
    {
      id: "G7",
      section: "grammar",
      tier: "Bridge",
      type: "mc",
      prompt: "I have lived here ___ 2022.",
      choices: ["since", "for", "ago", "during"],
      answer: "since",
      grammar: "present-perfect",
    },
    {
      id: "G8",
      section: "grammar",
      tier: "Bridge",
      type: "mc",
      prompt: "This route is ___ than the other one.",
      choices: ["shorter", "shortest", "more short", "the short"],
      answer: "shorter",
      grammar: "comparative",
    },
    {
      id: "G9",
      section: "grammar",
      tier: "Bridge",
      type: "mc",
      prompt: "You ___ wear a helmet when you ride a bike.",
      choices: ["must", "might", "would", "have"],
      answer: "must",
      grammar: "modal",
    },
    {
      id: "G10",
      section: "grammar",
      tier: "Bridge",
      type: "mc",
      prompt: "If it rains tomorrow, we ___ inside.",
      choices: ["will stay", "stayed", "have stayed", "staying"],
      answer: "will stay",
      grammar: "first-conditional",
    },
    {
      id: "G11",
      section: "grammar",
      tier: "Extension",
      type: "mc",
      prompt: "The girl ___ won the contest is my cousin.",
      choices: ["who", "which", "where", "whose"],
      answer: "who",
      grammar: "relative-clause",
    },
    {
      id: "G12",
      section: "grammar",
      tier: "Extension",
      type: "mc",
      prompt: "The machine ___ by our team last week.",
      choices: ["was tested", "tested", "is testing", "has test"],
      answer: "was tested",
      grammar: "passive",
    },

    {
      id: "R1",
      section: "reading",
      passageId: "bike_story",
      tier: "Core",
      type: "mc",
      prompt: "Why did Mia and Noah leave home early?",
      choices: [
        "They wanted to meet their friends at nine.",
        "They needed to buy a new bike.",
        "They wanted to visit the market first.",
        "Their parents asked them to leave.",
      ],
      answer: "They wanted to meet their friends at nine.",
    },
    {
      id: "R2",
      section: "reading",
      passageId: "bike_story",
      tier: "Core",
      type: "mc",
      prompt: "What problem happened on the way?",
      choices: [
        "Noah’s bike chain came off.",
        "Mia lost her phone.",
        "Their friends went home.",
        "It began to rain heavily.",
      ],
      answer: "Noah’s bike chain came off.",
    },
    {
      id: "R3",
      section: "reading",
      passageId: "bike_story",
      tier: "Bridge",
      type: "mc",
      prompt: "What did Noah learn from the mechanic?",
      choices: [
        "How to check the bike chain.",
        "How to ride faster.",
        "How to find the riverside park.",
        "How to call his friends.",
      ],
      answer: "How to check the bike chain.",
    },
    {
      id: "R4",
      section: "reading",
      passageId: "bike_story",
      tier: "Bridge",
      type: "mc",
      prompt: "In the story, “relieved” is closest to ____.",
      choices: [
        "happy because the problem was over",
        "angry about waiting",
        "afraid of the mechanic",
        "too tired to continue",
      ],
      answer: "happy because the problem was over",
      word: "relieved",
    },
    {
      id: "R5",
      section: "reading",
      passageId: "bottle_report",
      tier: "Core",
      type: "mc",
      prompt: "How many students carry a reusable bottle?",
      choices: ["18", "42", "60", "100"],
      answer: "18",
    },
    {
      id: "R6",
      section: "reading",
      passageId: "bottle_report",
      tier: "Bridge",
      type: "mc",
      prompt: "What is one advantage of Plan B?",
      choices: [
        "It is cheaper.",
        "It stops students from buying bottles.",
        "It includes a refill station.",
        "It gives every student a free bottle.",
      ],
      answer: "It is cheaper.",
    },
    {
      id: "R7",
      section: "reading",
      passageId: "bottle_report",
      tier: "Bridge",
      type: "mc",
      prompt: "Why will the class survey students again?",
      choices: [
        "To check whether the plan works.",
        "To choose a different class leader.",
        "To find the cheapest bottled drink.",
        "To decide where to put more desks.",
      ],
      answer: "To check whether the plan works.",
    },
    {
      id: "R8",
      section: "reading",
      passageId: "bottle_report",
      tier: "Extension",
      type: "mc",
      prompt: "Which sentence best states the class’s conclusion?",
      choices: [
        "Use a refill station and encourage reusable bottles.",
        "Recycling bins are the only useful solution.",
        "Students should stop drinking at school.",
        "The survey did not provide useful information.",
      ],
      answer: "Use a refill station and encourage reusable bottles.",
      word: "conclusion",
    },
  ];

  const performance = {
    writing: {
      title: "Writing｜短文",
      prompt:
        "Yesterday your team found a strange box in the library. Write 6–10 English sentences. Explain who was there, what happened, what you did, and how the story ended.",
      rubric: [
        {
          score: 0,
          label: "0｜未作答",
          description: "空白，或只有中文內容。",
        },
        {
          score: 1,
          label: "1｜單字／片段",
          description: "主要是零散單字或不完整片段，難以看出事件。",
        },
        {
          score: 2,
          label: "2｜簡單句",
          description: "至少 4 個可理解的簡單句；錯誤較多但大意可懂。",
        },
        {
          score: 3,
          label: "3｜連貫段落",
          description:
            "至少 6 句，會用 and、but、because、then 等連接，時態大致一致。",
        },
        {
          score: 4,
          label: "4｜清楚發展",
          description:
            "內容有開頭、發展、結尾，句型有變化，錯誤不妨礙理解。",
        },
      ],
    },
    speaking: {
      title: "Speaking｜口頭說明",
      prompt:
        "Choose one: (A) Explain how to get from your home to school. (B) Explain how you solve a simple problem. Speak in English for about 60 seconds.",
      rubric: [
        {
          score: 0,
          label: "0｜未作答",
          description: "沒有英文回答。",
        },
        {
          score: 1,
          label: "1｜零散單字",
          description: "只能說少量單字或背誦片段，需要持續提示。",
        },
        {
          score: 2,
          label: "2｜短句回答",
          description: "能用幾個簡單句回答，但停頓多、內容未連接。",
        },
        {
          score: 3,
          label: "3｜連接說明",
          description:
            "能連續說約 30–60 秒，使用順序、方向或原因表達。",
        },
        {
          score: 4,
          label: "4｜清楚完整",
          description:
            "能說約 60 秒，內容有組織，會補充理由或例子，容易理解。",
        },
      ],
    },
  };

  const bands = [
    {
      id: "foundation",
      label: "基礎重建（A1）",
      minPercent: 0,
      courseMode: "C",
      courseLabel: "C 鞏固模式",
      advice: "第 1 堂完整教學，Core 優先，降低新字量。",
    },
    {
      id: "a1plus",
      label: "A1+／A2 起步",
      minPercent: 40,
      courseMode: "C",
      courseLabel: "C 鞏固模式",
      advice: "第 1 堂完整教學，增加句框與口頭提取。",
    },
    {
      id: "a2",
      label: "A2 基礎",
      minPercent: 60,
      courseMode: "B",
      courseLabel: "B 標準模式",
      advice: "從第 1 堂標準進度開始，重點觀察主動字彙。",
    },
    {
      id: "a2plus",
      label: "A2+／六年級橋接",
      minPercent: 75,
      courseMode: "A",
      courseLabel: "A 加速模式",
      advice: "第 1 堂可壓縮複習，增加 Bridge 字與段落輸出。",
    },
    {
      id: "b1ready",
      label: "B1- 準備度",
      minPercent: 88,
      courseMode: "A",
      courseLabel: "A 加速模式",
      advice: "保留基礎查漏，優先加入閱讀、說明與修訂任務。",
    },
  ];

  return {
    id: "grade6-entry-diagnostic",
    version: "2026.07.24",
    title: "六年級英語起點診斷",
    sections,
    passages,
    questions,
    performance,
    bands,
  };
});
