// 國小英語 1200 字分級表（第 1～7 級，轉錄自家長提供 PDF；第 8 級不在檔內）。
// WORD_LEVELS[en] = 1..7。PDF 以外的字由 Codex 定級（見下方 EXTRA_LEVELS，8 = 超出 1200 / 國中以上）。
// 一字多級（如 may 6/7、garbage 6/7）取較低級。
const _L = {
  1: "a|an|am|are|arm|at|baby|bad|ball|bed|big|bird|boy|bus|car|card|cat|come|cup|desk|do|dog|door|ear|egg|eight|eye|fat|fine|five|food|four|girl|go|good|great|he|here|home|hot|how|i|in|is|it|job|jog|kid|king|leg|lion|love|lunch|man|milk|miss|moon|mr|mrs|ms|name|neck|new|nice|nine|no|nose|not|now|ok|one|or|pen|pet|picture|pie|pig|red|room|run|sad|say|seven|she|sit|six|sky|sun|tall|tea|ten|that|they|three|today|too|toy|tree|two|walk|water|we|what|who|yes|you",
  2: "air|and|ant|apple|bee|birthday|black|box|brother|brown|busy|but|cake|candy|cap|chair|classmate|classroom|clock|close|coffee|cola|coke|color|cow|cute|day|dear|dirty|doll|draw|eat|english|father|flower|fox|friendly|frog|fruit|give|glue|gray|green|ham|hello|hen|hey|hi|hippo|its|old|on|pencil|picnic|pink|please|read|real|rice|roc|ruler|sandwich|school|sea|see|sheep|ship|shirt|short|shy|sing|singer|sister|slow|small|sofa|son|song|soup|stand|store|student|study|table|talk|teacher|thank|these|those|toe|under|usa|very|want|wash|week|white|woman|year|yellow|zoo",
  3: "a.m.|about|after|afternoon|ago|america|animal|any|ask|autumn|bag|banana|beef|bicycle|bike|body|breakfast|chalk|child|coat|computer|cookie|cooky|cry|dad|daddy|dance|die|dining room|dinner|dollar|down|dress|drink|drive|dry|duck|elephant|eleven|eraser|evening|every|family|feel|fly|friend|good-bye|goodbye|hair|hand|hat|head|help|horse|hot dog|hour|house|hungry|ice|ice cream|into|invite|join|juice|kick|kiss|kitchen|kite|learn|money|morning|need|o'clock|p.m.|really|salt|sleep|spell|star|start|telephone|phone|there|together|train|trip|truck|try|up|wait|wear|weather|when|where|why|with|word|work|worker|write|yesterday|zero|true",
  4: "be|bookstore|bread|buy|cellphone|city|date|dig|dish|does|eighteen|eighty|even|fall|feed|fifteen|fifty|forty|fourteen|from|grandfather|grandpa|grandmother|grandma|homework|long|movie|never|news|newspaper|nineteen|ninety|of|office|out|page|paper|part|pay|pork|restaurant|road|salad|same|season|send|seventeen|seventy|sir|sixteen|sixty|size|skirt|smart|smell|snack|snake|snow|so|soccer|socks|some|soon|sound|speak|sports|spring|station|stay|steak|still|stop|street|strong|sugar|summer|sunny|sure|sweet|swim|tape|television|tv|thirsty|thirteen|thirty|this|tomorrow|twelve|twenty|use|vacation|vegetable|visit|wall|warm|weekend|wet|which|wind|window|winter|wonderful|worry|writer|wrong|young",
  5: "a few|a little|a lot|afraid|again|all|always|answer|anyone|anybody|anything|away|back|bake|basket|become|before|begin|blue|both|butter|careful|catch|chicken|class|cloudy|cook|cut|daughter|delicious|did|driver|each|early|easy|enjoy|enough|everybody|everyone|everything|face|farm|fast|fire|first|fish|forget|fork|friday|frisbee|garden|get|glad|goat|gym|hard|hate|hear|high|him|hop|hope|hotel|housewife|hundred|hurry|husband|large|last|left|lesson|lucky|many|marker|me|meet|monday|monkey|more|mother|mom|mommy|motorcycle|mountain|mouth|much|music|near|night|noon|number|nurse|often|once|only|open|orange|order|other|outside|over|pants|parent|party|pass|past|people|person|photo|pick|pin|pizza|place|plan|pool|practice|pray|prepare|present|price|problem|pull|puppy|purple|push|queen|question|quick|rabbit|radio|rain|rainy|remember|repeat|ride|right|robot|rope|row|safe|saturday|scared|second|seed|seldom|senior high school|several|shark|shoe|shoes|shout|skate|smile|snowman|sometimes|sorry|spoon|stamp|sunday|surf|taiwan|taxi|teach|tell|tennis|test|the|them|third|thursday|ticket|tiger|to|tonight|town|tuesday|understand|unhappy|us|usually|waiter|waitress|was|watch|wednesday|welcome|well|were|wife|win|windy|yard|your",
  6: "age|agree|airplane|plane|airport|also|angry|another|apartment|april|artist|august|bakery|baseball|basketball|bath|bathroom|beach|beautiful|because|bedroom|believe|between|blanket|blow|boat|borrow|boss|bottle|bottom|bun|camera|camp|care|cent|chance|cheap|cheese|china|chocolate|christmas|church|clap|clean|clerk|climb|club|cold|comb|comfortable|convenient|corner|cost|couch|count|cousin|crazy|dead|deaf|deal|december|decide|department store|dictionary|different|doctor|dodge ball|dodgeball|dot|dragon|drawer|drum|during|earth|east|easter|either|elementary school|else|e-mail|email|end|enter|eve|example|fact|factory|famous|far|farmer|favorite|february|few|fight|fill|finally|finger|finish|fisherman|fix|floor|follow|front|fun|gate|gift|glass|glove|goose|grape|guava|guitar|habit|hamburger|happen|health|heart|heavy|helpful|her|hide|hike|his|history|hobby|holiday|hospital|idea|important|insect|inside|jacket|january|july|june|kangaroo|knife|know|koala|late|lazy|lemon|let|library|like|lip|listen|little|live|living room|loud|lovely|low|mailman|mail carrier|map|march|market|math|mathematics|may|maybe|meeting|minute|month|most|mrt|museum|must|my|nail|noodle|north|november|october|oil|our|ox|papaya|peach|pear|piano|plate|pocket|pond|popcorn|post office|postcard|put|quiet|rat|ready|restroom|roller skate|rose|round|sale|science|sell|september|shake|shape|share|shopkeeper|shorts|sick|side|snowy|south|space|special|spider|story|strawberry|sweater|tail|their|thick|thin|thing|tie|necktie|tired|toast|tomato|tooth|trash|garbage|t-shirt|turkey|turtle|umbrella|useful|vest|video|voice|wallet|weak|west|will|wish|workbook|would",
  7: "across|action|actor|almost|around|avoid|badminton|band|bat|bear|been|behind|bell|belt|bench|beside|bite|blackboard|block|bored|boring|born|bowl|bring|bug|build|business|cage|can|could|candle|carry|castle|center|cheat|check|chess|chopsticks|clear|clothes|collect|comic|country|course|dangerous|dentist|done|dozen|dream|drop|ever|excited|exciting|excuse|exercise|find|flute|foot|french fries|fries|full|future|game|ghost|glasses|gram|grass|grow|guess|guy|halloween|handsome|happy|hard-working|healthy|hers|hold|honey|hunt|inch|interest|interested|interesting|island|itself|jeans|joy|jump|junior high school|just|keep|key|kill|kilogram|knee|knock|lake|lamp|land|lantern|later|laugh|leader|lend|letter|lid|life|list|look|lose|machine|mail|mask|mat|matter|might|meal|mean|meat|medicine|menu|mile|million|mistake|moment|mouse|mud|myself|nature|neighbor|next|nobody|nod|noise|notebook|nothing|ours|park|pe|physical education|pipe|playground|possible|pound|prince|princess|prize|railway|railroad|rainbow|recorder|refrigerator|reporter|rise|river|rock|screen|seat|seesaw|sharp|shop|should|shoulder|show|sidewalk|simple|since|someone|somebody|something|somewhere|spend|strange|stupid|surprised|swing|team|teenager|terrible|than|theirs|think|though|although|thousand|throw|time|top|total|towel|traffic|trouble|twice|typhoon|until|violin|wake|way|without|world|yet|yours|yourself|zebra"
};
const WORD_LEVELS = {};
for (const lv of [7, 6, 5, 4, 3, 2, 1])           // 低級後蓋 → 一字多級取較低
  _L[lv].split("|").forEach(w => { WORD_LEVELS[w] = lv; });

// PDF 以外的字：由 Codex 定級（1~6 比照難度，7 = 國中入門，8 = 更難）。
const EXTRA_LEVELS = {
};

function wordLevel(en) {
  const k = String(en || "").toLowerCase().trim();
  return WORD_LEVELS[k] || EXTRA_LEVELS[k] || null;
}
if (typeof module !== "undefined" && module.exports)
  module.exports = { WORD_LEVELS, EXTRA_LEVELS, wordLevel };
