// Grade 5 word bank — shared by daily drills and the vocab quiz.
// Each entry: { en, zh, theme }. Audio file = audio/words/<sanitized en>.mp3
const WORDBANK = [
  // family
  { en: "father", zh: "爸爸", theme: "family" },
  { en: "mother", zh: "媽媽", theme: "family" },
  { en: "brother", zh: "兄弟", theme: "family" },
  { en: "sister", zh: "姊妹", theme: "family" },
  { en: "parents", zh: "父母", theme: "family" },
  { en: "family", zh: "家庭", theme: "family" },
  { en: "uncle", zh: "叔叔", theme: "family" },
  { en: "aunt", zh: "阿姨", theme: "family" },
  { en: "cousin", zh: "表親", theme: "family" },
  { en: "grandpa", zh: "爺爺", theme: "family" },
  { en: "grandma", zh: "奶奶", theme: "family" },
  { en: "baby", zh: "嬰兒", theme: "family" },
  // animals
  { en: "dog", zh: "狗", theme: "animals" },
  { en: "cat", zh: "貓", theme: "animals" },
  { en: "bird", zh: "鳥", theme: "animals" },
  { en: "fish", zh: "魚", theme: "animals" },
  { en: "rabbit", zh: "兔子", theme: "animals" },
  { en: "turtle", zh: "烏龜", theme: "animals" },
  { en: "monkey", zh: "猴子", theme: "animals" },
  { en: "lion", zh: "獅子", theme: "animals" },
  { en: "tiger", zh: "老虎", theme: "animals" },
  { en: "elephant", zh: "大象", theme: "animals" },
  { en: "horse", zh: "馬", theme: "animals" },
  { en: "bear", zh: "熊", theme: "animals" },
  // food
  { en: "rice", zh: "米飯", theme: "food" },
  { en: "noodles", zh: "麵", theme: "food" },
  { en: "bread", zh: "麵包", theme: "food" },
  { en: "egg", zh: "蛋", theme: "food" },
  { en: "chicken", zh: "雞肉", theme: "food" },
  { en: "apple", zh: "蘋果", theme: "food" },
  { en: "banana", zh: "香蕉", theme: "food" },
  { en: "milk", zh: "牛奶", theme: "food" },
  { en: "water", zh: "水", theme: "food" },
  { en: "juice", zh: "果汁", theme: "food" },
  { en: "cake", zh: "蛋糕", theme: "food" },
  { en: "soup", zh: "湯", theme: "food" },
  // school
  { en: "school", zh: "學校", theme: "school" },
  { en: "teacher", zh: "老師", theme: "school" },
  { en: "student", zh: "學生", theme: "school" },
  { en: "classroom", zh: "教室", theme: "school" },
  { en: "desk", zh: "書桌", theme: "school" },
  { en: "chair", zh: "椅子", theme: "school" },
  { en: "book", zh: "書", theme: "school" },
  { en: "pencil", zh: "鉛筆", theme: "school" },
  { en: "eraser", zh: "橡皮擦", theme: "school" },
  { en: "ruler", zh: "尺", theme: "school" },
  { en: "bag", zh: "書包", theme: "school" },
  { en: "notebook", zh: "筆記本", theme: "school" },
  // clothes
  { en: "shirt", zh: "襯衫", theme: "clothes" },
  { en: "T-shirt", zh: "T恤", theme: "clothes" },
  { en: "pants", zh: "長褲", theme: "clothes" },
  { en: "shorts", zh: "短褲", theme: "clothes" },
  { en: "skirt", zh: "裙子", theme: "clothes" },
  { en: "dress", zh: "洋裝", theme: "clothes" },
  { en: "jacket", zh: "夾克", theme: "clothes" },
  { en: "coat", zh: "外套", theme: "clothes" },
  { en: "shoes", zh: "鞋子", theme: "clothes" },
  { en: "socks", zh: "襪子", theme: "clothes" },
  { en: "hat", zh: "帽子", theme: "clothes" },
  { en: "uniform", zh: "制服", theme: "clothes" },
  // weather
  { en: "sunny", zh: "晴朗", theme: "weather" },
  { en: "rainy", zh: "下雨", theme: "weather" },
  { en: "cloudy", zh: "多雲", theme: "weather" },
  { en: "windy", zh: "有風", theme: "weather" },
  { en: "hot", zh: "熱", theme: "weather" },
  { en: "cold", zh: "冷", theme: "weather" },
  { en: "warm", zh: "溫暖", theme: "weather" },
  { en: "cool", zh: "涼爽", theme: "weather" },
  { en: "weather", zh: "天氣", theme: "weather" },
  { en: "rain", zh: "雨", theme: "weather" },
  { en: "snow", zh: "雪", theme: "weather" },
  { en: "umbrella", zh: "雨傘", theme: "weather" },
  // body
  { en: "head", zh: "頭", theme: "body" },
  { en: "hair", zh: "頭髮", theme: "body" },
  { en: "face", zh: "臉", theme: "body" },
  { en: "eye", zh: "眼睛", theme: "body" },
  { en: "ear", zh: "耳朵", theme: "body" },
  { en: "nose", zh: "鼻子", theme: "body" },
  { en: "mouth", zh: "嘴巴", theme: "body" },
  { en: "hand", zh: "手", theme: "body" },
  { en: "arm", zh: "手臂", theme: "body" },
  { en: "leg", zh: "腿", theme: "body" },
  { en: "foot", zh: "腳", theme: "body" },
  { en: "body", zh: "身體", theme: "body" },
  // time
  { en: "morning", zh: "早上", theme: "time" },
  { en: "afternoon", zh: "下午", theme: "time" },
  { en: "evening", zh: "傍晚", theme: "time" },
  { en: "night", zh: "夜晚", theme: "time" },
  { en: "today", zh: "今天", theme: "time" },
  { en: "tomorrow", zh: "明天", theme: "time" },
  { en: "yesterday", zh: "昨天", theme: "time" },
  { en: "week", zh: "星期", theme: "time" },
  { en: "weekend", zh: "週末", theme: "time" },
  { en: "Monday", zh: "星期一", theme: "time" },
  { en: "Saturday", zh: "星期六", theme: "time" },
  { en: "Sunday", zh: "星期日", theme: "time" },
  // places
  { en: "home", zh: "家", theme: "places" },
  { en: "park", zh: "公園", theme: "places" },
  { en: "library", zh: "圖書館", theme: "places" },
  { en: "hospital", zh: "醫院", theme: "places" },
  { en: "market", zh: "市場", theme: "places" },
  { en: "store", zh: "商店", theme: "places" },
  { en: "restaurant", zh: "餐廳", theme: "places" },
  { en: "zoo", zh: "動物園", theme: "places" },
  { en: "bank", zh: "銀行", theme: "places" },
  { en: "station", zh: "車站", theme: "places" },
  { en: "museum", zh: "博物館", theme: "places" },
  // hobbies
  { en: "read", zh: "閱讀", theme: "hobbies" },
  { en: "draw", zh: "畫畫", theme: "hobbies" },
  { en: "sing", zh: "唱歌", theme: "hobbies" },
  { en: "dance", zh: "跳舞", theme: "hobbies" },
  { en: "swim", zh: "游泳", theme: "hobbies" },
  { en: "run", zh: "跑步", theme: "hobbies" },
  { en: "cook", zh: "烹飪", theme: "hobbies" },
  { en: "paint", zh: "油畫", theme: "hobbies" },
  { en: "game", zh: "遊戲", theme: "hobbies" },
  { en: "music", zh: "音樂", theme: "hobbies" },
  { en: "basketball", zh: "籃球", theme: "hobbies" },
  { en: "soccer", zh: "足球", theme: "hobbies" },
];

// Audio filename helper — must match generate_audio.py keying.
function wordAudioKey(en) {
  return en.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORDBANK, wordAudioKey };
}
