// 國小英語 1200 字分級表（第 1～7 級，轉錄自家長提供 PDF；第 8 級不在檔內）。
// WORD_LEVELS[en] = 1..7。PDF 以外的字由 Codex 定級（見下方 EXTRA_LEVELS，8 = 超出 1200 / 國中以上）。
// 一字多級（如 may 6/7、garbage 6/7）取較低級。
const _L = {
  1: "a|an|am|are|arm|at|baby|bad|ball|bed|big|bird|boy|bus|car|card|cat|come|cup|desk|do|dog|door|ear|egg|eight|eye|fat|fine|five|food|four|girl|go|good|great|he|here|home|hot|how|i|in|is|it|job|jog|kid|king|leg|lion|love|lunch|man|milk|miss|moon|mr|mrs|ms|name|neck|new|nice|nine|no|nose|not|now|ok|one|or|pen|pet|picture|pie|pig|red|room|run|sad|say|seven|she|sit|six|sky|sun|tall|tea|ten|that|they|three|today|too|toy|tree|two|walk|water|we|what|who|yes|you",
  2: "air|and|ant|apple|bee|birthday|black|box|brother|brown|busy|but|cake|candy|cap|chair|classmate|classroom|clock|close|coffee|cola|coke|color|cow|cute|day|dear|dirty|doll|draw|eat|english|father|flower|fox|friendly|frog|fruit|give|glue|gray|green|ham|hello|hen|hey|hi|hippo|its|old|on|pencil|picnic|pink|please|read|real|rice|roc|ruler|sandwich|school|sea|see|sheep|ship|shirt|short|shy|sing|singer|sister|slow|small|sofa|son|song|soup|stand|store|student|study|table|talk|teacher|thank|these|those|toe|under|usa|very|want|wash|week|white|woman|year|yellow|zoo",
  3: "a.m.|about|after|afternoon|ago|america|animal|any|ask|autumn|bag|banana|beef|bicycle|bike|body|breakfast|chalk|child|coat|computer|cookie|cooky|cry|dad|daddy|dance|die|dining room|dinner|dollar|down|dress|drink|drive|dry|duck|elephant|eleven|eraser|evening|every|family|feel|fly|friend|good-bye|goodbye|hair|hand|hat|head|help|horse|hot dog|hour|house|hungry|ice|ice cream|into|invite|join|juice|kick|kiss|kitchen|kite|learn|money|morning|need|o'clock|p.m.|really|salt|sleep|spell|star|start|telephone|phone|there|together|train|trip|truck|try|up|wait|wear|weather|when|where|why|with|word|work|worker|write|yesterday|zero|true",
  4: "be|bookstore|bread|buy|cellphone|city|date|dig|dish|does|eighteen|eighty|even|fall|feed|fifteen|fifty|forty|fourteen|from|grandfather|grandpa|grandmother|grandma|homework|long|movie|never|news|newspaper|nineteen|ninety|of|office|out|page|paper|part|pay|pork|restaurant|road|salad|same|season|send|seventeen|seventy|sir|sixteen|sixty|size|skirt|smart|smell|snack|snake|snow|so|soccer|socks|some|soon|sound|speak|sports|spring|station|stay|steak|still|stop|street|strong|sugar|summer|sunny|sure|sweet|swim|tape|television|tv|thirsty|thirteen|thirty|this|tomorrow|twelve|twenty|use|vacation|vegetable|visit|wall|warm|weekend|wet|which|wind|window|winter|wonderful|worry|writer|wrong|young",
  5: "a few|a little|a lot|afraid|again|all|always|answer|anyone|anybody|anything|away|back|bake|basket|become|before|begin|blue|both|butter|careful|catch|chicken|class|cloudy|cook|cut|daughter|delicious|did|driver|each|early|easy|enjoy|enough|everybody|everyone|everything|face|farm|fast|fire|first|fish|forget|fork|friday|frisbee|garden|get|glad|goat|gym|hard|hate|hear|high|him|hop|hope|hotel|housewife|hundred|hurry|husband|large|last|left|lesson|lucky|many|marker|me|meet|monday|monkey|more|mother|mom|mommy|motorcycle|mountain|mouth|much|music|near|night|noon|number|nurse|often|once|only|open|orange|order|other|outside|over|pants|parent|party|pass|past|people|person|photo|pick|pin|pizza|place|plan|pool|practice|pray|prepare|present|price|problem|pull|puppy|purple|push|queen|question|quick|rabbit|radio|rain|rainy|remember|repeat|ride|right|robot|rope|row|safe|saturday|scared|second|seed|seldom|senior high school|several|shark|shoe|shoes|shout|skate|smile|snowman|sometimes|sorry|spoon|stamp|sunday|surf|taiwan|taxi|teach|tell|tennis|test|the|them|third|thursday|ticket|tiger|to|tonight|town|tuesday|understand|unhappy|us|usually|waiter|waitress|was|watch|wednesday|welcome|well|were|wife|win|windy|yard|your",
  6: "age|agree|airplane|plane|airport|also|angry|another|apartment|april|artist|august|bakery|baseball|basketball|bath|bathroom|beach|beautiful|because|bedroom|believe|between|blanket|blow|boat|borrow|boss|bottle|bottom|bun|camera|camp|care|cent|chance|cheap|cheese|china|chocolate|christmas|church|clap|clean|clerk|climb|club|cold|comb|comfortable|convenient|corner|cost|couch|count|cousin|crazy|dead|deaf|deal|december|decide|department store|dictionary|different|doctor|dodge ball|dodgeball|dot|dragon|drawer|drum|during|earth|east|easter|either|elementary school|else|e-mail|email|end|enter|eve|example|fact|factory|famous|far|farmer|favorite|february|few|fight|fill|finally|finger|finish|fisherman|fix|floor|follow|front|fun|gate|gift|glass|glove|goose|grape|guava|guitar|habit|hamburger|happen|health|heart|heavy|helpful|her|hide|hike|his|history|hobby|holiday|hospital|idea|important|insect|inside|jacket|january|july|june|kangaroo|knife|know|koala|late|lazy|lemon|let|library|like|lip|listen|little|live|living room|loud|lovely|low|mailman|mail carrier|map|march|market|math|mathematics|may|maybe|meeting|minute|month|most|mrt|museum|must|my|nail|noodle|north|november|october|oil|our|ox|papaya|peach|pear|piano|plate|pocket|pond|popcorn|post office|postcard|put|quiet|rat|ready|restroom|roller skate|rose|round|sale|science|sell|september|shake|shape|share|shopkeeper|shorts|sick|side|snowy|south|space|special|spider|story|strawberry|sweater|tail|their|thick|thin|thing|tie|necktie|tired|toast|tomato|tooth|trash|garbage|t-shirt|turkey|turtle|umbrella|useful|vest|video|voice|wallet|weak|west|will|wish|workbook|would",
  7: "across|action|actor|almost|around|avoid|badminton|band|bat|bear|been|behind|bell|belt|bench|beside|bite|blackboard|block|bored|boring|born|bowl|bring|bug|build|business|cage|can|could|candle|carry|castle|center|cheat|check|chess|chopsticks|clear|clothes|collect|comic|country|course|dangerous|dentist|done|dozen|dream|drop|ever|excited|exciting|excuse|exercise|find|flute|foot|french fries|fries|full|future|game|ghost|glasses|gram|grass|grow|guess|guy|halloween|handsome|happy|hard-working|healthy|hers|hold|honey|hunt|inch|interest|interested|interesting|island|itself|jeans|joy|jump|junior high school|just|keep|key|kill|kilogram|knee|knock|lake|lamp|land|lantern|later|laugh|leader|lend|letter|lid|life|list|look|lose|machine|mail|mask|mat|matter|might|meal|mean|meat|medicine|menu|mile|million|mistake|moment|mouse|mud|myself|nature|neighbor|next|nobody|nod|noise|notebook|nothing|ours|park|pe|physical education|pipe|playground|possible|pound|prince|princess|prize|railway|railroad|rainbow|recorder|refrigerator|reporter|rise|river|rock|screen|seat|seesaw|sharp|shop|should|shoulder|show|sidewalk|simple|since|someone|somebody|something|somewhere|spend|strange|stupid|surprised|swing|team|teenager|terrible|than|theirs|think|though|although|thousand|throw|time|top|total|towel|traffic|trouble|twice|typhoon|until|violin|wake|way|without|world|yet|yours|yourself|zebra"
};
const WORD_LEVELS = {};
for (const lv of [7, 6, 5, 4, 3, 2, 1])           // 低級後蓋 → 一字多級取較低
  _L[lv].split("|").forEach(w => { WORD_LEVELS[w] = lv; });

// PDF 以外的字：由 Codex 定級（2026-07-06，1222 字；7 = 國小畢業~國中入門，8 = 國中以上）。
const _X = {
  2: "book|oh|play|wow",
  3: "aunt|call|children|cookies|drinks|make|oh-oh|oops|singing|take|uh-uh|uncle",
  4: "alphabet|balloon|bank|best|better|bus stop|butterfly|cd|chinese new year|cool|crayon|dancing|drawing|funny|in front of|kitten|kitty|light|next to|paint|panda|parents|pencil box|pencil case|pretty|reading|sport|swimming|yucky|yummy",
  5: "a lot of|add|already|bean|bicycle riding|board|bookcase|burger|button|calendar|carrot|cartoon|cd player|coin|computer game|corn|cream|deep|deer|diary|dinosaur|dolphin|donkey|doughnut|downstairs|dumpling|eagle|empty|exam|exit|family name|fast food|film|fire station|first grade|first name|fishing|flag|flower shop|football|france|french|fried chicken|fried rice|given name|granddaughter|grandson|haircut|hippopotamus|housework|in back of|jam|japan|jogging|kaohsiung|kind|lady|last name|leaf|leave|lot|lunch box|lychee|ma'am|mango|marry|match|melon|middle|milk shake|mirror|mix|monster|moon cake|mother's day|movie star|movie theater|new year's day|noodles|note|nut|onion|out of|pajamas|pan|pardon|parrot|paste|pepper|pillow|pineapple|pingpong|plant|plus|police officer|police station|policeman|pot|potato|print|printer|pumpkin|purse|puzzle|quickly|quiz|raincoat|reading test|rest|rude|rule|running|sand|scarf|second grade|shopping|shower|sink|skating|sleepy|slippers|snail|sneakers|soap|soda|soft drink|supper|surfing|table tennis|taichung|tainan|taipei|teacher's day|tent|tofu|toilet|toothache|toothbrush|train station|travel|traveling|tummy|ugly|upstairs|visitor|watermelon|weekday|wide|winner|worried",
  6: "act|addition|address|alarm|alarm clock|album|alone|aloud|angel|anywhere|armchair|arrive|asia|asleep|australia|awake|baby sitter|barber|bark|beard|beautifully|beginner|beginning|bit|bitter|blank|blouse|boil|bone|brave|brunch|building|cabbage|calm|camping|canada|carefully|careless|carpet|centimeter|cereal|chase|chin|choose|christmas eve|chubby|class leader|clever|climbing|closet|cloth|convenience store|cooking|cough|crab|crowded|curtain|daily|dessert|dizzy|double|double tenth day|downtown|dragon-boat festival|drama|dresser|drugstore|dryer|earrings|eighteenth|electric|electricity|eleventh|engine|entrance|envelope|error|expensive|extra|extra large|eyebrow|false|fast food restaurant|faucet|feeling|fever|fifteenth|fit|flashlight|flat tire|flu|fog|foggy|food restaurant|forest|fourteenth|freezer|freezing|fry|furniture|garage|gas station|get in|get off|get on|gloves|goal|gold|golden|golf|good looking|grapefruit|grow up|guest|hairdresser|hall|hang|hanger|headache|heater|hero|hiking|hip|hole|hong kong|ill|impolite|ink|instant noodle|japanese|jar|jeep|joke|ketchup|kilometer|kindergarten|ktv|lamb|lantern festival|lettuce|level|lock|locker|london|los angeles|mad|magazine|mall|mandarin|men's room|message|meter|michael jackson|microwave|microwave oven|mid-autumn festival|midnight|minus|missing|model|mop|mosquito|mountain-climbing|mtv|napkin|necklace|nest|new york|nice looking|nineteenth|ninetieth|noisy|ocean|outer space|oven|pain|painter|painting|paris|parking lot|passport|photograph|pigeon|plastic|pop music|primary school|quarter|race|receive|rectangle|relax|repair|reply|report|return|review|roll|roller skating|roof|rub|rubber|rubber band|running nose|rush|schoolmate|score|seafood|secret|seem|set|seventeenth|sheet|shelf|shine|shrimp|shut|sign|silly|silver|sixteenth|ski|skiing|skin|slide|soft|softball|sore throat|sour|soy-sauce|spaghetti|speaker|speed|stairs|stamp collecting|stationery|stationery store|step|stick|stomachache|stone|storm|stormy|stove|straight|straw|subject|subway|suitcase|swan|sweep|swimsuit|table cloth|taiwanese|tangerine|tape recorder|teapot|tear|temperature|temple|textbook|thirteenth|thirtieth|throat|thumb|thunder|tidy|till|tiny|tokyo|tongue|tool|tower|traffic jam|traffic light|traffic lights|traffic sign|trash can|triangle|trousers|trumpet|tub|twelfth|twentieth|underwear|unfriendly|uniform|used|usual|valentine's day|vcr|village|volleyball|waist|walkman|washing machine|waterfall|wave|weight|whale|wheel|wing|wolf|women's room|wonder|wood|wooden|woods|worse|wrist",
  7: "absent|accept|accident|active|activity|actress|adjective|adult|adventure|adverb|advice|advise|against|ahead|aim|air conditioner|airline|airmail|alike|alive|alley|allow|altogether|ambulance|among|anger|ankle|anyway|apologize|area|argue|army|arrange|article|asian|assistant|attack|attention|australian|backward|balcony|banker|bar|barbecue|base|basement|basic|beat|beer|behave|besides|bill|blood|both xxx and|bother|bow|bowling|boyfriend|brain|branch|brick|britain|british|bucket|buffet|cabinet|cable|cafeteria|campus|canadian|cancel|captain|cash|cassette|cause|ceiling|certainly|channel|chapter|character|chart|cheerleader|childhood|choice|clothing|coach|coast|cockroach|collection|college|comfortably|comment|company|compare|complete|congratulation|contact lens|continue|control|conversation|cotton|countryside|couple|create|credit card|crowd|customer|danger|death|decision|decorate|deliver|department|depend|describe|desert|design|dial|diamond|diet|difference|diligent|direction|disappear|discover|discuss|distance|divide|division|dumb|earn|eastern|elder|enemy|engineer|england|englishman|equal|especially|europe|european|event|everywhere|excite|exercising|expensive fruit|explain|fail|fair|fantastic|favor|fear|feather|fence|field|final|flat|flight|flour|fool|foolish|forward|friendship|frighten|gather|gentle|gentleman|german|germany|girlfriend|god|greedy|greet|guard|guide|gun|hammer|handkerchief|handle|hardly|height|helicopter|highway|homesick|horrible|huge|human|humid|hunger|hunter|illness|imagine|impossible|instrument|introduce|invitation|iron|italy|jazz|korea|korean|lane|lay|length|lift|lightning|link|loaf|loser|luggage|magician|main|male|manager|manner|meaning|mechanic|member|memory|metal|modern|movement|musician|narrow|natural|naughty|nearly|needle|neither|nephew|nervous|niece|none|northern|opinion|over-weight|overpass|owner|painful|pale|partner|passenger|path|patient|pattern|pause|peace|peaceful|perfect|period|philippines|photographer|pile|plain|pleasant|pleased|poem|popular|post|power|praise|prefer|primary|principal|project|promise|protect|pump|quit|raise|rare|rather|reach|reason|record|recycle|regular|remind|rent|republic of china|result|revise|rob|rome|root|russia|russian|safety|sail|sailing|sailor|salesman|sample|san francisco|saucer|scientist|search|secretary|select|selfish|semester|sense|serve|service|shoot|shore|shot|sight|silence|silent|simply|singapore|single|skinny|slender|slim|soldier|solve|sort|southern|stage|state|steal|steam|stingy|stream|style|such|sudden|suddenly|suit|tableware|talkative|term|terrific|thanksgiving|thanksgiving day|thief|through|tip|title|topic|tour|tourist|toward|track|treasure|treat|trick|trust|truth|tunnel|type|typewriter|under-weight|underpass|unit|valley|verb|victory|vinegar|vocabulary|war|waste|wedding|western|whatever|while|whole|wild|wine",
  8: "ability|abroad|achieve|admire|admit|adopt|advance|advantage|advertisement|affair|affect|aid|aids|aircraft|amount|ancient|appearance|apply|appreciate|arrest|as if|as soon as|as well as|assume|attend|audience|aux.v|auxiliary|available|aware|basis|being|belief|beyond|biology|blame|bomb|brief|broad|broadcast|bundle|burst|cancer|career|cell|central|century|certain|chairman|charge|chemical|chief|childish|childlike|citizen|claim|classic|classical|climate|command|complain|concern|confident|confirm|conflict|confuse|connective|consider|contain|contract|county|courage|court|creative|crime|crisis|cruel|culture|culture center|cure|curious|current|curve|custom|damage|data|dawn|debate|debt|degree|delay|democracy|democratic|deny|desire|detect|determine|determiner|develop|difficulty|diplomat|direct|director|discussion|dishonest|document|doubt|drug|duty|edge|education|effect|effective|effort|either xxx or|elect|election|element|emotion|emphasize|employ|encourage|energy|entire|environment|envy|even if|evil|exact|examine|exist|expect|experience|explore|express|failure|fancy|fashionable|fault|fellow|figure|firm|flow|focus|force|forgive|form|former|frank|freedom|function|gain|general|generally|generation|generous|geographical|geography|gesture|goodness|government|grand|hire|honesty|host|humble|humor|humorous|importance|improve|include|income|increase|indefinite|independent|industry|influence|information|insist|inspire|instant|intelligent|international|interrupt|interview|invent|jealous|journalist|judge|kingdom|lack|law|lawyer|ld|limit|liquid|local|location|loss|major|marriage|mass|master|material|maximum|measure|measurement|method|minor|motion|nation|nationality|necessary|negative|neither xxx nor|nor|not only xxx but also|num|o|obey|object|oc|occupation|occur|offer|official|omit|oneself|operate|operation|ordinary|organize|overseas|particular|personal|platform|pleasure|poison|pollute|pollution|population|port|position|positive|possessive|precious|preposition|president|press|priest|prison|prisoner|private|probably|produce|product|production|professor|progress|pronoun|pronounce|prove|provide|punish|purpose|quality|rapid|realize|recent|recently|recover|reflexive|refuse|regard|regret|reject|relative|require|respect|responsible|role|s|satisfied|satisfy|sc|scene|secondary|section|seek|separate|servant|shock|similar|sincere|skill|skillful|sneaky|social|social science|society|soul|speech|spirit|spread|standard|strike|struggle|submarine|succeed|success|successfully|suggest|support|surface|survive|swallow|symbol|talent|tank|task|therefore|thought|throughout|thus|trace|trade|tradition|traditional|transportation|trap|underlie|unique|universe|university|upon|valuable|value|vote|voter|whom|willing|within|worth|wound|youth|youth day",
};
const EXTRA_LEVELS = {};
for (const lv of Object.keys(_X)) _X[lv].split("|").forEach(w => { if (!(w in WORD_LEVELS)) EXTRA_LEVELS[w] = +lv; });

function wordLevel(en) {
  const k = String(en || "").toLowerCase().trim();
  return WORD_LEVELS[k] || EXTRA_LEVELS[k] || null;
}
if (typeof module !== "undefined" && module.exports)
  module.exports = { WORD_LEVELS, EXTRA_LEVELS, wordLevel };
