// Word -> emoji map for picturable vocabulary (built with Codex).
// Used by the vocab quiz for picture-style questions and hints.
// Abstract / grammatical words are intentionally omitted.
const WORD_EMOJI = {
  "beach": "🏖️", "mountain": "⛰️", "ticket": "🎫", "hotel": "🏨", "map": "🗺️", "airport": "🛫",
  "gift": "🎁", "luggage": "🧳", "passport": "🛂", "trip": "✈️", "vacation": "🏝️",
  "aircraft": "✈️", "alarm": "🚨", "alarm clock": "⏰", "ambulance": "🚑", "angel": "👼",
  "ant": "🐜", "badminton": "🏸", "balloon": "🎈", "bat": "🦇", "beer": "🍺",
  "bicycle riding": "🚴", "blood": "🩸", "bomb": "💣", "bone": "🦴", "bowling": "🎳",
  "brain": "🧠", "brick": "🧱", "bucket": "🪣", "bug": "🐛", "building": "🏢",
  "burger": "🍔", "bus stop": "🚏", "butterfly": "🦋", "calendar": "📅", "camping": "🏕️",
  "candle": "🕯️", "carrot": "🥕", "cassette": "📼", "castle": "🏰", "CD": "💿",
  "cereal": "🥣", "chart": "📊", "chess": "♟️", "climbing": "🧗", "cockroach": "🪳",
  "coin": "🪙", "computer game": "🎮", "convenience store": "🏪", "cookies": "🍪", "cooking": "🍳",
  "corn": "🌽", "crab": "🦀", "crayon": "🖍️", "credit card": "💳", "dawn": "🌅",
  "deer": "🦌", "desert": "🏜️", "diamond": "💎", "diary": "📔", "dinosaur": "🦕",
  "document": "📄", "dolphin": "🐬", "doughnut": "🍩", "dragon": "🐉", "drinks": "🥤",
  "drug": "💊", "drum": "🥁", "duck": "🦆", "dumpling": "🥟", "eagle": "🦅",
  "electricity": "⚡", "envelope": "✉️", "fast food": "🍔", "faucet": "🚰", "feather": "🪶",
  "film": "🎞️", "fishing": "🎣", "flag": "🚩", "flashlight": "🔦", "fog": "🌫️",
  "foggy": "🌫️", "football": "🏈", "fox": "🦊", "French fries": "🍟", "fried chicken": "🍗",
  "Frisbee": "🥏", "frog": "🐸", "gas station": "⛽", "ghost": "👻", "glasses": "👓",
  "gloves": "🧤", "goal": "🥅", "golf": "⛳", "grape": "🍇", "guitar": "🎸",
  "gun": "🔫", "hammer": "🔨", "helicopter": "🚁", "hen": "🐔", "highway": "🛣️",
  "hippo": "🦛", "hippopotamus": "🦛", "hole": "🕳️", "honey": "🍯", "instant noodle": "🍜",
  "jeep": "🚙", "jogging": "🏃", "kangaroo": "🦘", "koala": "🐨", "lantern": "🏮",
  "leaf": "🍃", "lettuce": "🥬", "lightning": "⚡", "lock": "🔒", "loaf": "🍞",
  "lunch box": "🍱", "mango": "🥭", "mask": "😷", "melon": "🍈", "men's room": "🚹",
  "milk shake": "🥤", "mirror": "🪞", "moon cake": "🥮", "mosquito": "🦟", "mountain-climbing": "🧗",
  "movie theater": "🎦", "MRT": "🚇", "nail": "💅", "necktie": "👔", "needle": "🪡",
  "newspaper": "📰", "noodles": "🍜", "nut": "🥜", "ocean": "🌊", "onion": "🧅",
  "outer space": "🌌", "ox": "🐂", "pan": "🍳", "panda": "🐼", "parking lot": "🅿️",
  "parrot": "🦜", "peach": "🍑", "pear": "🍐", "pepper": "🌶️", "photo": "🖼️",
  "photograph": "🖼️", "pin": "📌", "pineapple": "🍍", "pingpong": "🏓", "plant": "🪴",
  "plate": "🍽️", "police officer": "👮", "policeman": "👮", "potato": "🥔", "primary school": "🏫",
  "prince": "🤴", "princess": "👸", "printer": "🖨️", "prize": "🏆", "pumpkin": "🎃",
  "puppy": "🐶", "purse": "👛", "puzzle": "🧩", "railroad": "🛤️", "rat": "🐀",
  "robot": "🤖", "rock": "🪨", "roller skating": "🛼", "sail": "⛵", "sailing": "⛵",
  "scarf": "🧣", "screen": "🖥️", "shark": "🦈", "shoes": "👞", "shopping": "🛍️",
  "shorts": "🩳", "shower": "🚿", "shrimp": "🦐", "sign": "🪧", "singing": "🎤",
  "skate": "🛼", "skating": "🛼", "ski": "🎿", "skiing": "🎿", "slippers": "🩴",
  "snail": "🐌", "sneakers": "👟", "snowman": "☃️", "snowy": "❄️", "soap": "🧼",
  "soccer": "⚽", "soda": "🥤", "soft drink": "🥤", "softball": "🥎", "spaghetti": "🍝",
  "speaker": "🔈", "spider": "🕷️", "stone": "🪨", "storm": "⛈️", "stormy": "⛈️",
  "strawberry": "🍓", "subway": "🚇", "suitcase": "🧳", "surf": "🏄", "surfing": "🏄",
  "swan": "🦢", "swimming": "🏊", "swimsuit": "🩱", "table tennis": "🏓", "tableware": "🍽️",
  "tangerine": "🍊", "teapot": "🫖", "temple": "🛕", "tent": "⛺", "textbook": "📘",
  "thumb": "👍", "thunder": "🌩️", "tie": "👔", "toast": "🍞", "toilet": "🚽",
  "tongue": "👅", "toothbrush": "🪥", "tower": "🗼", "traffic light": "🚥", "traffic lights": "🚦",
  "train station": "🚉", "trash can": "🗑️", "triangle": "🔺", "trousers": "👖", "trumpet": "🎺",
  "T-shirt": "👕", "tub": "🛁", "turkey": "🦃", "turtle": "🐢", "underwear": "🩲",
  "universe": "🌌", "village": "🏘️", "violin": "🎻", "volleyball": "🏐", "watermelon": "🍉",
  "wave": "🌊", "wedding": "💒", "whale": "🐋", "wine": "🍷", "wolf": "🐺",
  "women's room": "🚺", "wood": "🪵", "zebra": "🦓", "zero": "0️⃣",
  "baby": "👶", "dog": "🐶", "cat": "🐱", "bird": "🐦", "fish": "🐟",
  "rabbit": "🐰", "monkey": "🐵", "lion": "🦁", "tiger": "🐯", "elephant": "🐘",
  "horse": "🐴", "bear": "🐻", "rice": "🍚", "bread": "🍞", "egg": "🥚",
  "chicken": "🍗", "apple": "🍎", "banana": "🍌", "milk": "🥛", "water": "💧",
  "juice": "🧃", "cake": "🍰", "soup": "🍲", "school": "🏫", "chair": "🪑",
  "book": "📖", "pencil": "✏️", "ruler": "📏", "bag": "🎒", "notebook": "📓",
  "shirt": "👕", "pants": "👖", "skirt": "👗", "dress": "👗", "jacket": "🧥",
  "coat": "🧥", "socks": "🧦", "hat": "🎩", "sunny": "☀️", "rainy": "🌧️",
  "cloudy": "☁️", "windy": "🌬️", "rain": "🌧️", "snow": "❄️", "umbrella": "☂️",
  "face": "🙂", "eye": "👁️", "ear": "👂", "nose": "👃", "mouth": "👄",
  "hand": "✋", "arm": "💪", "leg": "🦵", "foot": "🦶", "morning": "🌅",
  "evening": "🌆", "night": "🌙", "home": "🏠", "park": "🏞️", "hospital": "🏥",
  "store": "🏬", "restaurant": "🍽️", "bank": "🏦", "station": "🚉", "museum": "🏛️",
  "game": "🎮", "music": "🎵", "basketball": "🏀"
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORD_EMOJI };
}
