// 文法根基課程（2026-07-10 定稿；Claude 起草、Codex 覆審）
// 原則：不求一年學完，觀念根基優先；順序不是進度表，學穩再前進。
// 不教：被動、關係子句、間接引述、完成式家族。
const GRAMMAR_CORE = [
  { id: "u1", kind: "unit", name: "句子是什麼", eng: "What Is a Sentence?", icon: "🏗️", weeks: "2-3",
    concept: "誰＋做什麼（主詞＋動詞）；直述/疑問/命令/驚嘆四種句型",
    diagram: "句子工廠：左邊放主詞、右邊放動詞，輸出四種句子",
    podcastKey: "英文句子一定要有主詞和動詞" },
  { id: "u2", kind: "unit", name: "名詞與 a/an/the", eng: "Nouns & Articles", icon: "🧸", weeks: "2-3",
    concept: "一個/很多個（單複數）；a/an 第一次提到、the 你我都知道",
    diagram: "名詞分兩堆（一個/很多個），旁邊 a/an/the 三張貼紙",
    podcastKey: "a/an 是第一次、the 是你我都知道" },
  { id: "u3", kind: "unit", name: "代名詞家族", eng: "Pronouns", icon: "🎭", weeks: "2",
    concept: "I/me/my/mine 一家四口；位置不同穿不同衣服",
    diagram: "代名詞換裝表：I/me/my/mine 像四種制服",
    podcastKey: "位置不同，代名詞衣服不同" },
  { id: "u4", kind: "unit", name: "兩種動詞引擎", eng: "Be vs. Action Verbs", icon: "⚙️", weeks: "3",
    concept: "be 動詞（是/在/狀態）vs 一般動詞（動作）——最重要的分水嶺",
    diagram: "兩台引擎：be 引擎 vs action 引擎，一台車只能裝一台",
    podcastKey: "be 動詞和一般動詞不要混在同一台車" },
  { id: "r1", kind: "review", name: "綜合複習：造句工廠", eng: "Review: Sentence Factory", icon: "🏭", weeks: "2",
    concept: "把名詞、代名詞、be/一般動詞組成正確句子",
    diagram: "造句輸送帶：零件（名詞/代名詞/動詞）組裝成句",
    podcastKey: "先造對，再造長" },
  { id: "u5", kind: "unit", name: "現在簡單式", eng: "Present Simple", icon: "🔁", weeks: "3",
    concept: "習慣與事實（不是現在正在！）；三單 s",
    diagram: "日常循環圈：every day / usually / 事實 圍著圓圈",
    podcastKey: "現在簡單不是現在正在，是習慣和事實" },
  { id: "u6", kind: "unit", name: "現在進行式", eng: "Present Continuous", icon: "🔍", weeks: "2",
    concept: "現在正在做什麼；be + V-ing 是一組",
    diagram: "放大鏡看 right now 正在發生的動作",
    podcastKey: "be + V-ing 是一組，不可拆" },
  { id: "u7", kind: "unit", name: "過去簡單式", eng: "Past Simple", icon: "📖", weeks: "3",
    concept: "把事情放進「昨天盒子」；規則 -ed＋常用不規則",
    diagram: "昨天的故事相簿：regular / irregular 兩本相簿",
    podcastKey: "過去式是把事情放進昨天盒子" },
  { id: "r2", kind: "review", name: "綜合複習：時間軸", eng: "Review: Timeline", icon: "🛤️", weeks: "2-3",
    concept: "yesterday / every day / right now / later 四個站牌",
    diagram: "一條時間軸，四個站牌各接一種動詞形狀",
    podcastKey: "看時間詞決定動詞形狀" },
  { id: "u8", kind: "unit", name: "問句與否定", eng: "Questions & Negatives", icon: "🤖", weeks: "3",
    concept: "do/does/did 小幫手；not 的位置",
    diagram: "小幫手機器人：一般動詞問句/否定要請它出場",
    podcastKey: "一般動詞問句否定要請小幫手" },
  { id: "u9", kind: "unit", name: "描述員", eng: "Describing Words", icon: "🏷️", weeks: "2-3",
    concept: "形容詞貼名詞、副詞貼動作、頻率副詞貼習慣",
    diagram: "貼標籤：形容詞→名詞、副詞→動作、always~never 量表",
    podcastKey: "形容詞說東西怎樣，副詞說動作怎樣" },
  { id: "u10", kind: "unit", name: "位置與時間", eng: "Prepositions", icon: "🗺️", weeks: "2",
    concept: "空間介係詞（圖感）＋ at/on/in 時間金字塔",
    diagram: "空間地圖＋at/on/in 金字塔",
    podcastKey: "介係詞不是翻中文，是看空間關係" },
  { id: "r3", kind: "review", name: "綜合複習：描述我的一天", eng: "Review: My Day", icon: "🌅", weeks: "2",
    concept: "用時態＋描述詞＋介係詞說完整的一天",
    diagram: "一天行程漫畫：起床、上學、吃飯、回家",
    podcastKey: "用時間＋動作＋描述，說完整一天" },
  { id: "u11", kind: "unit", name: "連接詞", eng: "Conjunctions", icon: "🌉", weeks: "2",
    concept: "and/but/or/so/because 五座橋",
    diagram: "句子橋梁：五座橋各自代表兩句的關係",
    podcastKey: "連接詞不是裝飾，是說明兩句的關係" },
  { id: "u12", kind: "unit", name: "好用的小幫手", eng: "Helpers: can / there is / will", icon: "🧰", weeks: "2-3",
    concept: "can（能力）＋There is/are（存在）＋will / be going to 入門；should/must 為補充",
    diagram: "工具箱：can、there is/are、will/going to 三件工具",
    podcastKey: "小幫手後面動詞回原形" },
  { id: "r4", kind: "review", name: "總複習：句子合體", eng: "Review: Build Paragraphs", icon: "🧪", weeks: "2+",
    concept: "把全部觀念合體，寫短段落（自我介紹/日記）",
    diagram: "句子合體實驗室：短句合成一段話",
    podcastKey: "文法最後要服務表達，不是背規則" }
];
if (typeof module !== "undefined" && module.exports) module.exports = { GRAMMAR_CORE };
