// 各級字彙池（wL1-6）單字練習題用的例句庫。key 用小寫、跟 wordlevels.js 的字完全一致。
// 每個字一句簡短自然例句，供 render_pool_quiz.js 產生單字練習題（含發音、四選一中文意思）。
const SENTENCES = {
  // ===== Lv1 (106) =====
  a: "I have a pen.", am: "I am seven years old.", an: "I see an apple.", are: "We are happy.",
  arm: "I hurt my arm.", at: "The cat is at home.", baby: "The baby is sleeping.", bad: "That was a bad day.",
  ball: "Throw me the ball.", bed: "I sleep in my bed.", big: "The elephant is big.", bird: "A bird can fly.",
  boy: "The boy is running.", bus: "We take the bus to school.", car: "My dad drives a car.", card: "I made a birthday card.",
  cat: "The cat is sleeping.", come: "Please come here.", cup: "I drink milk from a cup.", desk: "My book is on the desk.",
  do: "What do you do after school?", dog: "The dog is barking.", door: "Please close the door.", ear: "Rabbits have long ears.",
  egg: "I eat an egg for breakfast.", eight: "I have eight crayons.", eye: "Close your eyes.", fat: "The cat is fat.",
  fine: "I am fine, thank you.", five: "I have five fingers.", food: "The food smells good.", four: "There are four seasons.",
  girl: "The girl is singing.", go: "Let's go to the park.", good: "You did a good job.", great: "That is a great idea.",
  he: "He is my brother.", here: "Come here, please.", home: "I go home at five.", hot: "The soup is hot.",
  how: "How are you today?", i: "I like ice cream.", in: "The book is in the bag.", is: "This is my dog.",
  it: "It is raining.", job: "My mom has a busy job.", jog: "I jog every morning.", kid: "The kid is playing outside.",
  king: "The king lives in a castle.", leg: "I hurt my leg.", lion: "A lion is a big cat.", love: "I love my family.",
  lunch: "We eat lunch at noon.", man: "The man is tall.", milk: "I drink milk every day.", miss: "I miss my grandma.",
  moon: "I can see the moon tonight.", mr: "This is Mr. Wang.", mrs: "This is Mrs. Chen.", ms: "This is Ms. Lin.",
  name: "My name is Amy.", neck: "The giraffe has a long neck.", new: "I got a new bag.", nice: "You are very nice.",
  nine: "The movie starts at nine.", no: "No, thank you.", nose: "My nose is cold.", not: "This is not my pen.",
  now: "Let's go now.", ok: "Are you OK?", one: "I have one sister.", or: "Do you want tea or milk?",
  pen: "May I borrow your pen?", pet: "My pet is a cat.", picture: "Look at this picture.", pie: "We baked an apple pie.",
  pig: "The pig lives on the farm.", red: "The apple is red.", room: "Clean your room, please.", run: "I run every morning.",
  sad: "Don't be sad.", say: "What did you say?", seven: "School starts at seven.", she: "She is my friend.",
  sit: "Please sit down.", six: "I wake up at six.", sky: "The sky is blue.", sun: "The sun is bright today.",
  tall: "My brother is very tall.", tea: "My grandma likes hot tea.", ten: "I count from one to ten.", that: "That is a nice hat.",
  they: "They are my classmates.", three: "I have three pencils.", today: "Today is a sunny day.", too: "I like apples, too.",
  toy: "This is my favorite toy.", tree: "A bird sits in the tree.", two: "I have two hands.", walk: "We walk to school together.",
  water: "Please drink more water.", we: "We are best friends.", what: "What is your name?", who: "Who is that boy?",
  yes: "Yes, I am ready.", you: "How are you?",

  // ===== Lv2 (101) =====
  air: "We breathe fresh air outside.", and: "I like apples and bananas.", ant: "A tiny ant is on the table.",
  apple: "I eat an apple every day.", bee: "A bee flies to the flower.", birthday: "Today is my birthday.",
  black: "My shoes are black.", box: "I put my toys in a box.", brother: "My brother is ten years old.",
  brown: "The dog has brown fur.", busy: "My mom is very busy today.", but: "I like tea, but not coffee.",
  cake: "We made a chocolate cake.", candy: "The candy is very sweet.", cap: "He wears a red cap.",
  chair: "Please sit on the chair.", classmate: "She is my classmate.", classroom: "Our classroom is very clean.",
  clock: "The clock says three o'clock.", close: "Please close the window.", coffee: "My dad drinks coffee every morning.",
  coke: "I like coke better than juice.", cola: "We drank cola at the party.", color: "What is your favorite color?",
  cow: "The cow eats grass.", cute: "The puppy is very cute.", day: "It is a sunny day.", dear: "Dear friend, how are you?",
  dirty: "My shoes are dirty.", doll: "She plays with her doll.", draw: "I like to draw animals.",
  eat: "Let's eat dinner together.", english: "We study English at school.", father: "My father works in the city.",
  flower: "This flower smells nice.", fox: "A fox ran across the field.", friendly: "Our new neighbor is very friendly.",
  frog: "The frog jumped into the pond.", fruit: "I eat fruit every day.", give: "Can you give me the ball?",
  glue: "Use glue to stick the paper.", gray: "The sky is gray today.", green: "The grass is green.",
  ham: "We had ham sandwiches for lunch.", hello: "Hello, how are you?", hen: "The hen laid an egg.",
  hey: "Hey, look at this!", hi: "Hi, my name is Tom.", hippo: "The hippo swims in the river.",
  its: "The dog wagged its tail.", old: "My grandpa is very old.", on: "The book is on the table.",
  pencil: "May I borrow your pencil?", picnic: "We had a picnic in the park.", pink: "She wears a pink dress.",
  please: "Please help me.", read: "I like to read books.", real: "That flower looks real.",
  rice: "We eat rice every day.", roc: "The roc is a giant bird in stories.", ruler: "Use a ruler to draw a line.",
  sandwich: "I made a cheese sandwich.", school: "I go to school by bus.", sea: "We swam in the sea.",
  see: "I can see a rainbow.", sheep: "The sheep are in the field.", ship: "The ship sailed across the ocean.",
  shirt: "He wears a blue shirt.", short: "My hair is short.", shy: "The little boy is shy.",
  sing: "She loves to sing songs.", singer: "My sister wants to be a singer.", sister: "My sister is eight years old.",
  slow: "The turtle is very slow.", small: "The mouse is very small.", sofa: "We sat on the sofa.",
  son: "He is their only son.", song: "This is my favorite song.", soup: "The soup is warm and tasty.",
  stand: "Please stand up.", store: "We bought bread at the store.", student: "I am a student at this school.",
  study: "I study English every night.", table: "Put the plate on the table.", talk: "Let's talk about the trip.",
  teacher: "My teacher is very kind.", thank: "Thank you for your help.", these: "These are my new shoes.",
  those: "Those are my friends.", toe: "I stubbed my toe.", under: "The cat is under the table.",
  usa: "My uncle lives in the USA.", very: "This cake is very sweet.", want: "I want a glass of water.",
  wash: "Please wash your hands.", week: "I have music class every week.", white: "The snow is white.",
  woman: "That woman is my teacher.", year: "I am nine years old this year.", yellow: "The sun is yellow.",
  zoo: "We saw a lion at the zoo.",

  // ===== Lv3 (103) =====
  "a.m.": "I wake up at seven a.m.", about: "Tell me about your day.", after: "We play after school.",
  afternoon: "I do my homework in the afternoon.", ago: "I visited Japan two years ago.",
  america: "My cousin lives in America.", animal: "My favorite animal is the panda.", any: "Do you have any questions?",
  ask: "You can ask the teacher for help.", autumn: "The leaves fall in autumn.", bag: "I put my books in my bag.",
  banana: "I eat a banana every morning.", beef: "We had beef noodles for dinner.", bicycle: "I ride my bicycle to school.",
  bike: "My bike is blue.", body: "Exercise is good for your body.", breakfast: "I eat breakfast at seven.",
  chalk: "The teacher writes with chalk.", child: "The child is playing in the park.", coat: "Wear your coat, it's cold.",
  computer: "I do my homework on the computer.", cookie: "She baked chocolate cookies.", cooky: "That was a cooky little joke.",
  cry: "The baby began to cry.", dad: "My dad cooks dinner every night.", daddy: "Daddy, can you help me?",
  dance: "We dance at the party.", die: "Plants die without water.", "dining room": "We eat dinner in the dining room.",
  dinner: "We eat dinner at six.", dollar: "The toy costs one dollar.", down: "Please sit down.",
  dress: "She wears a pretty dress.", drink: "I drink water every day.", drive: "My mom drives me to school.",
  dry: "The towel is dry now.", duck: "The duck swims in the pond.", elephant: "The elephant is very big.",
  eleven: "I go to bed at eleven.", eraser: "May I borrow your eraser?", evening: "We watch TV in the evening.",
  every: "I brush my teeth every day.", family: "I love my family.", feel: "How do you feel today?",
  fly: "Birds can fly high.", friend: "She is my best friend.", "good-bye": "Good-bye, see you tomorrow!",
  goodbye: "Goodbye, see you tomorrow!", hair: "My sister has long hair.", hand: "Raise your hand if you know.",
  hat: "He wears a big hat.", head: "My head hurts a little.", help: "Can you help me with this?",
  horse: "The horse runs very fast.", "hot dog": "I ate a hot dog for lunch.", hour: "It takes one hour to get there.",
  house: "Our house has a big garden.", hungry: "I am hungry after school.", ice: "The lake turned to ice.",
  "ice cream": "I love chocolate ice cream.", into: "The cat jumped into the box.", invite: "I will invite my friends to my party.",
  join: "Do you want to join us?", juice: "I drink orange juice for breakfast.", kick: "He can kick the ball far.",
  kiss: "Mom gave me a kiss goodnight.", kitchen: "My mom is cooking in the kitchen.", kite: "We flew a kite in the park.",
  learn: "I learn new words every day.", money: "I saved my money to buy a toy.", morning: "I eat breakfast every morning.",
  need: "I need a new pencil.", "o'clock": "It is three o'clock now.", "p.m.": "School ends at four p.m.",
  phone: "My mom is talking on the phone.", really: "I am really happy today.", salt: "Please pass the salt.",
  sleep: "I sleep eight hours a night.", spell: "Can you spell your name?", star: "I can see a star in the sky.",
  start: "The movie will start soon.", telephone: "The telephone is ringing.", there: "Put the box over there.",
  together: "We did our homework together.", train: "We took the train to the city.", trip: "We had a fun trip to the beach.",
  truck: "The truck carried many boxes.", true: "Is this story true?", try: "You can try again.",
  up: "Please stand up.", wait: "Please wait for me.", wear: "I wear a jacket in winter.",
  weather: "The weather is nice today.", when: "When is your birthday?", where: "Where is my bag?",
  why: "Why are you late?", with: "I go to school with my sister.", word: "Can you spell this word?",
  work: "My dad goes to work early.", worker: "The worker fixed the door.", write: "Please write your name here.",
  yesterday: "I played soccer yesterday.", zero: "The score is zero to zero.",

  // ===== Lv4 (107) =====
  be: "I want to be a doctor.", bookstore: "We bought books at the bookstore.", bread: "I eat bread for breakfast.",
  buy: "I want to buy a new bike.", cellphone: "My cellphone is in my bag.", city: "Taipei is a big city.",
  date: "What is today's date?", dig: "The dog likes to dig in the yard.", dish: "Please wash the dish.",
  does: "Does she like apples?", eighteen: "My cousin is eighteen years old.", eighty: "My grandpa is eighty years old.",
  even: "Even my little brother can swim.", fall: "Leaves fall in autumn.", feed: "I feed my dog every morning.", fifteen: "There are fifteen students in my class.",
  fifty: "The book costs fifty dollars.", forty: "My mom is forty years old.", fourteen: "My sister is fourteen years old.",
  from: "This letter is from my grandma.", grandfather: "My grandfather tells great stories.",
  grandma: "My grandma bakes cookies for me.", grandmother: "My grandmother lives in the countryside.",
  grandpa: "My grandpa likes to fish.", homework: "I finish my homework every night.", long: "The river is very long.",
  movie: "We watched a movie last night.", never: "I never eat breakfast late.", news: "My dad watches the news every day.",
  newspaper: "My dad reads the newspaper every morning.", nineteen: "My brother is nineteen years old.",
  ninety: "The old clock is ninety years old.", of: "This is a picture of my family.", office: "My mom works in an office.",
  out: "The cat ran out of the room.", page: "Turn to page ten.", paper: "Please write on this paper.",
  part: "This is my favorite part of the story.", pay: "I will pay for the tickets.", pork: "We had pork for dinner.",
  restaurant: "We ate dinner at a restaurant.", road: "Cars drive on the road.", salad: "I had a salad for lunch.",
  same: "We wear the same shoes.", season: "Summer is my favorite season.", send: "I will send you a letter.",
  seventeen: "My brother is seventeen years old.", seventy: "My grandma is seventy years old.",
  sir: "Excuse me, sir, can you help me?", sixteen: "My cousin is sixteen years old.", sixty: "The bus ride takes sixty minutes.",
  size: "What size shoes do you wear?", skirt: "She wears a blue skirt.", smart: "My sister is very smart.",
  smell: "This flower has a sweet smell.", snack: "I have a snack after school.", snake: "The snake moved quietly through the grass.",
  snow: "It started to snow this morning.", so: "I was tired, so I went to bed.", soccer: "We play soccer after school.",
  socks: "I wear warm socks in winter.", some: "I want some water, please.", soon: "The bus will arrive soon.",
  sound: "I heard a strange sound.", speak: "Can you speak English?", sports: "I like watching sports on TV.",
  spring: "Flowers bloom in spring.", station: "We waited at the train station.", stay: "I will stay home today.",
  steak: "My dad cooked steak for dinner.", still: "It is still raining outside.", stop: "Please stop at the red light.",
  street: "We walked down the street.", strong: "My dad is very strong.", sugar: "I don't want sugar in my tea.",
  summer: "We swim a lot in summer.", sunny: "It is a sunny day.", sure: "Are you sure about that?",
  sweet: "This cake is very sweet.", swim: "I like to swim in the pool.", tape: "Use tape to fix the paper.",
  television: "We watch television after dinner.", thirsty: "I am thirsty after running.",
  thirteen: "My sister is thirteen years old.", thirty: "The movie is thirty minutes long.", this: "This is my new bag.",
  tomorrow: "We have a test tomorrow.", tv: "I watch TV after dinner.", twelve: "There are twelve months in a year.",
  twenty: "There are twenty students in my class.", use: "You can use my pencil.", vacation: "We went to the beach on vacation.",
  vegetable: "I eat a vegetable with every meal.", visit: "We will visit my grandma this weekend.",
  wall: "There is a picture on the wall.", warm: "It is warm today.", weekend: "I play soccer on the weekend.",
  wet: "My shoes are wet from the rain.", which: "Which color do you like best?", wind: "The wind is very strong today.",
  window: "Please open the window.", winter: "It snows a lot in winter.", wonderful: "We had a wonderful trip.",
  worry: "Don't worry, everything will be fine.", writer: "She wants to be a writer.", wrong: "I chose the wrong answer.",
  young: "My little brother is very young.",

  // ===== Lv5 (193) =====
  "a few": "I have a few apples left.", "a little": "I want a little more rice.", "a lot": "I have a lot of homework today.",
  afraid: "I am afraid of the dark.", again: "Let's play this game again.", all: "All my friends came to the party.",
  always: "She always helps her friends.", answer: "Do you know the answer?", anybody: "Is anybody home?",
  anyone: "Does anyone want more juice?", anything: "I didn't eat anything for breakfast.", away: "The bird flew away.",
  back: "I will be back soon.", bake: "We bake cookies on Sundays.", basket: "Put the apples in the basket.",
  become: "I want to become a teacher.", before: "Wash your hands before dinner.", begin: "The class will begin soon.",
  blue: "The sky is blue today.", both: "I like both apples and bananas.", butter: "Spread butter on the bread.",
  careful: "Be careful on the stairs.", catch: "Can you catch the ball?", chicken: "We had chicken for dinner.",
  class: "My class has thirty students.", cloudy: "It is cloudy today.", cook: "My mom likes to cook.",
  cut: "Please cut the paper carefully.", daughter: "She is their only daughter.", delicious: "This soup is delicious.",
  did: "Did you finish your homework?", driver: "My uncle is a bus driver.", each: "Each student gets a book.",
  early: "I wake up early every day.", easy: "This math problem is easy.", enjoy: "I enjoy playing basketball.",
  enough: "We have enough food for everyone.", everybody: "Everybody is here now.", everyone: "Everyone likes the new teacher.",
  everything: "Everything is ready for the trip.", face: "Wash your face before bed.", farm: "My grandpa has a small farm.",
  fast: "The rabbit ran very fast.", fire: "We sat around the fire.", first: "She was the first to finish.",
  fish: "We caught a fish in the lake.", forget: "Don't forget your umbrella.", fork: "Please pass me a fork.",
  friday: "We have a test on Friday.", frisbee: "We played frisbee at the park.", garden: "My mom grows flowers in the garden.",
  get: "I get up at seven every day.", glad: "I am glad you are here.", goat: "The goat ate the grass.",
  gym: "We exercise in the gym.", hard: "This question is very hard.", hate: "I hate being late for school.",
  hear: "Can you hear the birds singing?", high: "The mountain is very high.", him: "I gave him my pencil.",
  hop: "The rabbit began to hop.", hope: "I hope it doesn't rain tomorrow.", hotel: "We stayed at a nice hotel.",
  housewife: "My aunt is a busy housewife.", hundred: "There are one hundred students in our grade.",
  hurry: "Hurry, or we will be late!", husband: "Her husband works at a hospital.", large: "The elephant is very large.",
  last: "This is the last question.", left: "Turn left at the corner.", lesson: "Our English lesson starts at nine.",
  lucky: "I feel very lucky today.", many: "I have many friends at school.", marker: "I drew a picture with a marker.",
  me: "Can you help me, please?", meet: "Let's meet at the library.", mom: "My mom makes great pancakes.",
  mommy: "Mommy, can I have a cookie?", monday: "We have art class on Monday.", monkey: "The monkey climbed the tree.",
  more: "May I have more rice, please?", mother: "My mother works at a hospital.", motorcycle: "My uncle rides a motorcycle.",
  mountain: "We hiked up the mountain.", mouth: "Open your mouth wide.", much: "I don't have much time.",
  music: "I love listening to music.", near: "The park is near my house.", night: "I read a book every night.",
  noon: "We eat lunch at noon.", number: "What is your phone number?", nurse: "My aunt is a kind nurse.",
  often: "I often walk to school.", once: "I visit my aunt once a month.", only: "She is the only girl in her class.",
  open: "Please open the door.", orange: "I ate a sweet orange.", order: "Can I order a pizza?",
  other: "I have two other pencils.", outside: "We play outside after school.", over: "The game is over now.",
  pants: "He wears black pants.", parent: "Each parent came to the school event.", party: "We had a birthday party.",
  pass: "Please pass the salt.", past: "The bus just went past our house.", people: "Many people came to the festival.",
  person: "She is a very kind person.", photo: "We took a photo at the park.", pick: "I will pick you up after school.",
  pin: "She wore a pretty pin on her jacket.", pizza: "We ordered pizza for dinner.", place: "This park is a nice place to play.",
  plan: "What is your plan for today?", pool: "We swim in the pool every summer.", practice: "I practice piano every day.",
  pray: "We pray before dinner.", prepare: "I prepare my bag the night before.", present: "This is a present for you.",
  price: "The price of the toy is low.", problem: "I have a math problem to solve.", pull: "Please pull the door open.",
  puppy: "Our new puppy is very playful.", purple: "She wears a purple dress.", push: "Push the door to open it.",
  queen: "The queen lives in a castle.", question: "I have a question for you.", quick: "That was a quick answer.",
  rabbit: "The rabbit hopped across the yard.", radio: "My dad listens to the radio in the car.",
  rain: "The rain stopped in the afternoon.", rainy: "It is a rainy day.", remember: "I remember my first day of school.",
  repeat: "Can you repeat that, please?", ride: "I ride my bike to school.", right: "Turn right at the next corner.",
  robot: "My little brother loves his toy robot.", rope: "We used a rope to climb the tree.", row: "We sat in the first row.",
  safe: "Wear a helmet to stay safe.", saturday: "We visit grandma every Saturday.", scared: "I was scared of the thunder.",
  second: "Wait a second, please.", seed: "We planted a seed in the garden.", seldom: "I seldom eat fast food.",
  "senior high school": "My sister goes to senior high school.", several: "I have several books to read.",
  shark: "We saw a shark at the aquarium.", shoe: "This shoe is too small.", shoes: "I need new shoes for school.",
  shout: "Please don't shout in the library.", skate: "We skate at the park on weekends.", smile: "She always has a big smile.",
  snowman: "We built a snowman in the yard.", sometimes: "I sometimes walk to school.", sorry: "I am sorry I was late.",
  spoon: "Please give me a spoon.", stamp: "I collect stamps from other countries.", sunday: "We go to the park on Sunday.",
  surf: "We tried to surf at the beach.", taiwan: "I was born in Taiwan.", taxi: "We took a taxi to the airport.",
  teach: "My mom teaches math at school.", tell: "Can you tell me a story?", tennis: "We play tennis on weekends.",
  test: "I studied hard for the test.", the: "The sun is shining today.", them: "I gave them my old toys.",
  third: "This is the third question.", thursday: "We have music class on Thursday.", ticket: "I bought a ticket for the movie.",
  tiger: "The tiger is a strong animal.", to: "I go to school by bus.", tonight: "We will watch a movie tonight.",
  town: "My grandma lives in a small town.", tuesday: "We have PE class on Tuesday.", understand: "I understand this lesson now.",
  unhappy: "She looked unhappy after the game.", us: "Please help us with our homework.", usually: "I usually walk to school.",
  waiter: "The waiter brought us the menu.", waitress: "The waitress was very friendly.", was: "It was a fun day.",
  watch: "I watch cartoons on Saturday morning.", wednesday: "We have art class on Wednesday.", welcome: "Welcome to our school!",
  well: "She sings very well.", were: "We were at the park yesterday.", wife: "His wife is a doctor.",
  win: "I hope our team will win.", windy: "It is very windy today.", yard: "We play in the yard after school.",
  your: "Is this your bag?",

  // ===== Lv6 (243) =====
  age: "What is your age?", agree: "I agree with your idea.", airplane: "We flew on an airplane to Japan.",
  airport: "We waited at the airport for our flight.", also: "I also like drawing.", angry: "My mom was angry when I was late.",
  another: "Can I have another cookie?", apartment: "We live in a small apartment.", april: "My birthday is in April.",
  artist: "She wants to be an artist.", august: "School starts again in August.", bakery: "We bought bread at the bakery.",
  baseball: "My brother plays baseball every weekend.", basketball: "We played basketball after school.",
  bath: "I take a bath every night.", bathroom: "The bathroom is upstairs.", beach: "We swam at the beach.",
  beautiful: "The sunset was beautiful.", because: "I stayed home because I was sick.", bedroom: "My bedroom is on the second floor.",
  believe: "I believe you can do it.", between: "The park is between two schools.", blanket: "I sleep with a warm blanket.",
  blow: "The wind began to blow hard.", boat: "We rode a boat across the lake.", borrow: "Can I borrow your pencil?",
  boss: "My mom's boss is very kind.", bottle: "Please fill my water bottle.", bottom: "The toy fell to the bottom of the box.",
  bun: "I ate a sweet bun for breakfast.", camera: "My dad bought a new camera.", camp: "We went to summer camp last year.",
  care: "Take care of your little sister.", cent: "The candy costs fifty cents.", chance: "Give me a chance to try again.",
  cheap: "This toy is very cheap.", cheese: "I like cheese on my sandwich.", china: "My grandma was born in China.",
  chocolate: "I love chocolate ice cream.", christmas: "We decorate a tree at Christmas.", church: "We go to church on Sunday.",
  clap: "Everyone began to clap.", clean: "Please clean your room.", clerk: "The clerk helped me find the book.",
  climb: "We like to climb trees.", club: "I joined the art club.", cold: "It is very cold today.",
  comb: "Use a comb to fix your hair.", comfortable: "This chair is very comfortable.", convenient: "The bus stop is very convenient.",
  corner: "The store is on the corner.", cost: "How much does this cost?", couch: "We watched TV on the couch.",
  count: "Can you count to one hundred?", cousin: "My cousin visits us every summer.", crazy: "That was a crazy idea.",
  dead: "The plant looks dead.", deaf: "My grandpa is a little deaf.", deal: "It's not a big deal.",
  december: "We have winter break in December.", decide: "I can't decide which one to choose.",
  "department store": "We bought new shoes at the department store.", dictionary: "Use a dictionary to check the spelling.",
  different: "Our shoes are different colors.", doctor: "My aunt is a doctor.", "dodge ball": "We played dodge ball in gym class.",
  dodgeball: "We played dodgeball in gym class.", dot: "Connect the dots to make a picture.",
  dragon: "The dragon danced in the parade.", drawer: "I keep my socks in the drawer.", drum: "My brother plays the drum.",
  during: "We were quiet during the movie.", "e-mail": "I sent an e-mail to my teacher.",
  earth: "The earth moves around the sun.", east: "The sun rises in the east.", easter: "We paint eggs at Easter.",
  either: "You can choose either one.", "elementary school": "I study at an elementary school.",
  else: "Does anyone else want juice?", email: "I sent an email to my teacher.", end: "We were sad at the end of the trip.",
  enter: "Please enter the classroom quietly.", eve: "We stayed up late on New Year's Eve.",
  example: "Can you give me an example?", fact: "Here is an interesting fact about whales.",
  factory: "My uncle works at a factory.", famous: "She is a famous singer.", far: "The school is not far from my house.",
  farmer: "The farmer grows rice and vegetables.", favorite: "Pizza is my favorite food.", february: "My birthday is in February.",
  few: "Only a few students were late.", fight: "The brothers had a small fight.", fill: "Please fill the cup with water.",
  finally: "We finally arrived home.", finger: "I hurt my finger.", finish: "I will finish my homework soon.",
  fisherman: "The fisherman caught a big fish.", fix: "My dad can fix the bike.", floor: "The toy fell on the floor.",
  follow: "Please follow me to the classroom.", front: "Wait for me in front of the school.", fun: "We had so much fun today.",
  garbage: "Please take out the garbage.", gate: "We waited at the school gate.", gift: "Thank you for the birthday gift.",
  glass: "Please give me a glass of water.", glove: "I wear gloves in winter.", goose: "A goose is bigger than a duck.",
  grape: "I ate a bunch of grapes.", guava: "Guava is my favorite fruit.", guitar: "My sister is learning to play the guitar.",
  habit: "Brushing your teeth is a good habit.", hamburger: "We ate hamburgers for lunch.", happen: "What happened at school today?",
  health: "Exercise is good for your health.", heart: "My heart beats fast when I run.", heavy: "This box is very heavy.",
  helpful: "My classmate is very helpful.", her: "This is her book.", hide: "Let's play hide and seek.",
  hike: "We went on a hike last weekend.", his: "This is his bike.", history: "I like learning about history.",
  hobby: "My hobby is drawing.", holiday: "We visited grandma during the holiday.", hospital: "My mom works at the hospital.",
  idea: "That is a great idea.", important: "Sleep is important for your health.", insect: "A ladybug is a small insect.",
  inside: "Let's go inside, it's cold.", jacket: "Wear your jacket, it's chilly.", january: "We start a new year in January.",
  july: "We have summer vacation in July.", june: "School ends in June.", kangaroo: "A kangaroo can jump very high.",
  knife: "Be careful with the knife.", know: "I know the answer.", koala: "A koala sleeps most of the day.",
  late: "I was late for school today.", lazy: "Don't be lazy, finish your homework.", lemon: "This drink tastes like lemon.",
  let: "Let me help you with that.", library: "We borrowed books from the library.", like: "I like reading books.",
  lip: "She has a cut on her lip.", listen: "Please listen to the teacher.", little: "The little dog is very cute.",
  live: "We live near the school.", "living room": "We watch TV in the living room.", loud: "The music was too loud.",
  lovely: "What a lovely day!", low: "The plane flew low over the field.", "mail carrier": "The mail carrier brings letters every day.",
  mailman: "The mailman brings letters every day.", map: "Use the map to find the way.", march: "Spring begins in March.",
  market: "We buy vegetables at the market.", math: "Math is my favorite subject.", mathematics: "Mathematics can be fun.",
  may: "It may rain tomorrow.", maybe: "Maybe we can go tomorrow.", meeting: "My mom has a meeting at work.",
  minute: "Wait one minute, please.", month: "My birthday is next month.", most: "Most students like recess.",
  mrt: "We took the MRT to the museum.", museum: "We visited the art museum.", must: "You must wear a helmet.",
  my: "This is my school bag.", nail: "I hurt my nail.", necktie: "My dad wears a necktie to work.",
  noodle: "I love eating noodle soup.", north: "We drove north to the mountains.", november: "It gets cold in November.",
  october: "We celebrate a festival in October.", oil: "Add a little oil to the pan.", our: "This is our classroom.",
  ox: "The ox pulled the cart.", papaya: "Papaya is sweet and orange.", peach: "I ate a juicy peach.",
  pear: "This pear is very sweet.", piano: "She practices piano every day.", plane: "We took a plane to Japan.",
  plate: "Please put the food on the plate.", pocket: "I keep my keys in my pocket.", pond: "There are fish in the pond.",
  popcorn: "We ate popcorn at the movies.", "post office": "I mailed the letter at the post office.",
  postcard: "I sent a postcard from my trip.", put: "Please put your shoes here.", quiet: "Please be quiet in the library.",
  rat: "A rat ran across the yard.", ready: "Are you ready for school?", restroom: "Where is the nearest restroom?",
  "roller skate": "I got new roller skates for my birthday.", rose: "She gave me a red rose.", round: "The ball is round.",
  sale: "The toy store is having a sale.", science: "We did an experiment in science class.", sell: "The shop sells fresh fruit.",
  september: "School starts again in September.", shake: "Let's shake hands.", shape: "What shape is this box?",
  share: "Please share your toys with your sister.", shopkeeper: "The shopkeeper was very friendly.",
  shorts: "I wear shorts in summer.", sick: "I stayed home because I was sick.", side: "Walk on the right side of the road.",
  snowy: "It was a snowy morning.", south: "We drove south to the beach.", space: "Astronauts travel into space.",
  special: "Today is a special day.", spider: "A spider made a web in the garden.", story: "My grandma tells great stories.",
  strawberry: "I love strawberry ice cream.", sweater: "Wear a sweater, it's cold outside.",
  "t-shirt": "I wear a T-shirt in summer.", tail: "The dog wagged its tail.", their: "This is their house.",
  thick: "The book is very thick.", thin: "The paper is very thin.", thing: "What is that thing on the table?",
  tie: "My dad wears a tie to work.", tired: "I am tired after playing all day.", toast: "I eat toast for breakfast.",
  tomato: "I put tomato in my salad.", tooth: "I lost a tooth yesterday.", trash: "Please throw the trash away.",
  turkey: "We ate turkey on Thanksgiving.", turtle: "The turtle moved very slowly.", umbrella: "Bring your umbrella, it might rain.",
  useful: "This tool is very useful.", vest: "He wears a vest over his shirt.", video: "We watched a funny video.",
  voice: "She has a beautiful singing voice.", wallet: "My dad keeps his money in his wallet.",
  weak: "I felt weak after being sick.", west: "The sun sets in the west.", will: "I will finish my homework soon.",
  wish: "I wish you a happy birthday.", workbook: "Please open your workbook to page five.", would: "Would you like some tea?",
};
if (typeof module !== "undefined" && module.exports) module.exports = { SENTENCES };
