// 各級字彙池（wL1-6）單字練習題用的例句庫。key 用小寫、跟 wordlevels.js 的字完全一致。
// 每個字一句簡短自然例句，供 render_pool_quiz.js 產生單字練習題（含發音、四選一中文意思）。
const SENTENCES = {
  // ===== Lv1 (106) =====
  a: "I have a pen.", am: "I am seven years old.", an: "I see an apple.", are: "We are happy.",
  arm: "I hurt my arm.", at: "The cat is at home.", baby: "The baby is sleeping.", bad: "That was a bad day.",
  ball: "Throw me the ball.", bed: "I sleep in my bed.", big: "The elephant is big.", bird: "A bird can fly.",
  boy: "The boy is running.", bus: "We take the bus to school.", car: "My dad drives a car.", card: "I made a birthday card.",
  cat: "The cat is sleeping.", come: "Please come here.", cup: "I drink milk from a cup.", desk: "My book is on the desk.",
  do: "What do you do after school?", dog: "The dog is barking.", door: "Please close the door.", ear: "Rabbits have long ears.",
  egg: "I eat an egg for breakfast.", eight: "I have eight crayons.", eye: "Close your eyes.", fat: "The cat is fat.",
  fine: "I am fine, thank you.", five: "I have five fingers.", food: "The food smells good.", four: "There are four seasons.",
  girl: "The girl is singing.", go: "Let's go to the park.", good: "You did a good job.", great: "That is a great idea.",
  he: "He is my brother.", here: "Come here, please.", home: "I go home at five.", hot: "The soup is hot.",
  how: "How are you today?", i: "I like ice cream.", in: "The book is in the bag.", is: "This is my dog.",
  it: "It is raining.", job: "My mom has a busy job.", jog: "I jog every morning.", kid: "The kid is playing outside.",
  king: "The king lives in a castle.", leg: "I hurt my leg.", lion: "A lion is a big cat.", love: "I love my family.",
  lunch: "We eat lunch at noon.", man: "The man is tall.", milk: "I drink milk every day.", miss: "I miss my grandma.",
  moon: "I can see the moon tonight.", mr: "This is Mr. Wang.", mrs: "This is Mrs. Chen.", ms: "This is Ms. Lin.",
  name: "My name is Amy.", neck: "The giraffe has a long neck.", new: "I got a new bag.", nice: "You are very nice.",
  nine: "The movie starts at nine.", no: "No, thank you.", nose: "My nose is cold.", not: "This is not my pen.",
  now: "Let's go now.", ok: "Are you OK?", one: "I have one sister.", or: "Do you want tea or milk?",
  pen: "May I borrow your pen?", pet: "My pet is a cat.", picture: "Look at this picture.", pie: "We baked an apple pie.",
  pig: "The pig lives on the farm.", red: "The apple is red.", room: "Clean your room, please.", run: "I run every morning.",
  sad: "Don't be sad.", say: "What did you say?", seven: "School starts at seven.", she: "She is my friend.",
  sit: "Please sit down.", six: "I wake up at six.", sky: "The sky is blue.", sun: "The sun is bright today.",
  tall: "My brother is very tall.", tea: "My grandma likes hot tea.", ten: "I count from one to ten.", that: "That is a nice hat.",
  they: "They are my classmates.", three: "I have three pencils.", today: "Today is a sunny day.", too: "I like apples, too.",
  toy: "This is my favorite toy.", tree: "A bird sits in the tree.", two: "I have two hands.", walk: "We walk to school together.",
  water: "Please drink more water.", we: "We are best friends.", what: "What is your name?", who: "Who is that boy?",
  yes: "Yes, I am ready.", you: "How are you?",

  // ===== Lv2 (101) =====
  air: "We breathe fresh air outside.", and: "I like apples and bananas.", ant: "A tiny ant is on the table.",
  apple: "I eat an apple every day.", bee: "A bee flies to the flower.", birthday: "Today is my birthday.",
  black: "My shoes are black.", box: "I put my toys in a box.", brother: "My brother is ten years old.",
  brown: "The dog has brown fur.", busy: "My mom is very busy today.", but: "I like tea, but not coffee.",
  cake: "We made a chocolate cake.", candy: "The candy is very sweet.", cap: "He wears a red cap.",
  chair: "Please sit on the chair.", classmate: "She is my classmate.", classroom: "Our classroom is very clean.",
  clock: "The clock says three o'clock.", close: "Please close the window.", coffee: "My dad drinks coffee every morning.",
  coke: "I like coke better than juice.", cola: "We drank cola at the party.", color: "What is your favorite color?",
  cow: "The cow eats grass.", cute: "The puppy is very cute.", day: "It is a sunny day.", dear: "Dear friend, how are you?",
  dirty: "My shoes are dirty.", doll: "She plays with her doll.", draw: "I like to draw animals.",
  eat: "Let's eat dinner together.", english: "We study English at school.", father: "My father works in the city.",
  flower: "This flower smells nice.", fox: "A fox ran across the field.", friendly: "Our new neighbor is very friendly.",
  frog: "The frog jumped into the pond.", fruit: "I eat fruit every day.", give: "Can you give me the ball?",
  glue: "Use glue to stick the paper.", gray: "The sky is gray today.", green: "The grass is green.",
  ham: "We had ham sandwiches for lunch.", hello: "Hello, how are you?", hen: "The hen laid an egg.",
  hey: "Hey, look at this!", hi: "Hi, my name is Tom.", hippo: "The hippo swims in the river.",
  its: "The dog wagged its tail.", old: "My grandpa is very old.", on: "The book is on the table.",
  pencil: "May I borrow your pencil?", picnic: "We had a picnic in the park.", pink: "She wears a pink dress.",
  please: "Please help me.", read: "I like to read books.", real: "That flower looks real.",
  rice: "We eat rice every day.", roc: "The roc is a giant bird in stories.", ruler: "Use a ruler to draw a line.",
  sandwich: "I made a cheese sandwich.", school: "I go to school by bus.", sea: "We swam in the sea.",
  see: "I can see a rainbow.", sheep: "The sheep are in the field.", ship: "The ship sailed across the ocean.",
  shirt: "He wears a blue shirt.", short: "My hair is short.", shy: "The little boy is shy.",
  sing: "She loves to sing songs.", singer: "My sister wants to be a singer.", sister: "My sister is eight years old.",
  slow: "The turtle is very slow.", small: "The mouse is very small.", sofa: "We sat on the sofa.",
  son: "He is their only son.", song: "This is my favorite song.", soup: "The soup is warm and tasty.",
  stand: "Please stand up.", store: "We bought bread at the store.", student: "I am a student at this school.",
  study: "I study English every night.", table: "Put the plate on the table.", talk: "Let's talk about the trip.",
  teacher: "My teacher is very kind.", thank: "Thank you for your help.", these: "These are my new shoes.",
  those: "Those are my friends.", toe: "I stubbed my toe.", under: "The cat is under the table.",
  usa: "My uncle lives in the USA.", very: "This cake is very sweet.", want: "I want a glass of water.",
  wash: "Please wash your hands.", week: "I have music class every week.", white: "The snow is white.",
  woman: "That woman is my teacher.", year: "I am nine years old this year.", yellow: "The sun is yellow.",
  zoo: "We saw a lion at the zoo.",

  // ===== Lv3 (103) =====
  "a.m.": "I wake up at seven a.m.", about: "Tell me about your day.", after: "We play after school.",
  afternoon: "I do my homework in the afternoon.", ago: "I visited Japan two years ago.",
  america: "My cousin lives in America.", animal: "My favorite animal is the panda.", any: "Do you have any questions?",
  ask: "You can ask the teacher for help.", autumn: "The leaves fall in autumn.", bag: "I put my books in my bag.",
  banana: "I eat a banana every morning.", beef: "We had beef noodles for dinner.", bicycle: "I ride my bicycle to school.",
  bike: "My bike is blue.", body: "Exercise is good for your body.", breakfast: "I eat breakfast at seven.",
  chalk: "The teacher writes with chalk.", child: "The child is playing in the park.", coat: "Wear your coat, it's cold.",
  computer: "I do my homework on the computer.", cookie: "She baked chocolate cookies.", cooky: "That was a cooky little joke.",
  cry: "The baby began to cry.", dad: "My dad cooks dinner every night.", daddy: "Daddy, can you help me?",
  dance: "We dance at the party.", die: "Plants die without water.", "dining room": "We eat dinner in the dining room.",
  dinner: "We eat dinner at six.", dollar: "The toy costs one dollar.", down: "Please sit down.",
  dress: "She wears a pretty dress.", drink: "I drink water every day.", drive: "My mom drives me to school.",
  dry: "The towel is dry now.", duck: "The duck swims in the pond.", elephant: "The elephant is very big.",
  eleven: "I go to bed at eleven.", eraser: "May I borrow your eraser?", evening: "We watch TV in the evening.",
  every: "I brush my teeth every day.", family: "I love my family.", feel: "How do you feel today?",
  fly: "Birds can fly high.", friend: "She is my best friend.", "good-bye": "Good-bye, see you tomorrow!",
  goodbye: "Goodbye, see you tomorrow!", hair: "My sister has long hair.", hand: "Raise your hand if you know.",
  hat: "He wears a big hat.", head: "My head hurts a little.", help: "Can you help me with this?",
  horse: "The horse runs very fast.", "hot dog": "I ate a hot dog for lunch.", hour: "It takes one hour to get there.",
  house: "Our house has a big garden.", hungry: "I am hungry after school.", ice: "The lake turned to ice.",
  "ice cream": "I love chocolate ice cream.", into: "The cat jumped into the box.", invite: "I will invite my friends to my party.",
  join: "Do you want to join us?", juice: "I drink orange juice for breakfast.", kick: "He can kick the ball far.",
  kiss: "Mom gave me a kiss goodnight.", kitchen: "My mom is cooking in the kitchen.", kite: "We flew a kite in the park.",
  learn: "I learn new words every day.", money: "I saved my money to buy a toy.", morning: "I eat breakfast every morning.",
  need: "I need a new pencil.", "o'clock": "It is three o'clock now.", "p.m.": "School ends at four p.m.",
  phone: "My mom is talking on the phone.", really: "I am really happy today.", salt: "Please pass the salt.",
  sleep: "I sleep eight hours a night.", spell: "Can you spell your name?", star: "I can see a star in the sky.",
  start: "The movie will start soon.", telephone: "The telephone is ringing.", there: "Put the box over there.",
  together: "We did our homework together.", train: "We took the train to the city.", trip: "We had a fun trip to the beach.",
  truck: "The truck carried many boxes.", true: "Is this story true?", try: "You can try again.",
  up: "Please stand up.", wait: "Please wait for me.", wear: "I wear a jacket in winter.",
  weather: "The weather is nice today.", when: "When is your birthday?", where: "Where is my bag?",
  why: "Why are you late?", with: "I go to school with my sister.", word: "Can you spell this word?",
  work: "My dad goes to work early.", worker: "The worker fixed the door.", write: "Please write your name here.",
  yesterday: "I played soccer yesterday.", zero: "The score is zero to zero.",

  // ===== Lv4 (107) =====
  be: "I want to be a doctor.", bookstore: "We bought books at the bookstore.", bread: "I eat bread for breakfast.",
  buy: "I want to buy a new bike.", cellphone: "My cellphone is in my bag.", city: "Taipei is a big city.",
  date: "What is today's date?", dig: "The dog likes to dig in the yard.", dish: "Please wash the dish.",
  does: "Does she like apples?", eighteen: "My cousin is eighteen years old.", eighty: "My grandpa is eighty years old.",
  even: "Even my little brother can swim.", fall: "Leaves fall in autumn.", feed: "I feed my dog every morning.", fifteen: "There are fifteen students in my class.",
  fifty: "The book costs fifty dollars.", forty: "My mom is forty years old.", fourteen: "My sister is fourteen years old.",
  from: "This letter is from my grandma.", grandfather: "My grandfather tells great stories.",
  grandma: "My grandma bakes cookies for me.", grandmother: "My grandmother lives in the countryside.",
  grandpa: "My grandpa likes to fish.", homework: "I finish my homework every night.", long: "The river is very long.",
  movie: "We watched a movie last night.", never: "I never eat breakfast late.", news: "My dad watches the news every day.",
  newspaper: "My dad reads the newspaper every morning.", nineteen: "My brother is nineteen years old.",
  ninety: "The old clock is ninety years old.", of: "This is a picture of my family.", office: "My mom works in an office.",
  out: "The cat ran out of the room.", page: "Turn to page ten.", paper: "Please write on this paper.",
  part: "This is my favorite part of the story.", pay: "I will pay for the tickets.", pork: "We had pork for dinner.",
  restaurant: "We ate dinner at a restaurant.", road: "Cars drive on the road.", salad: "I had a salad for lunch.",
  same: "We wear the same shoes.", season: "Summer is my favorite season.", send: "I will send you a letter.",
  seventeen: "My brother is seventeen years old.", seventy: "My grandma is seventy years old.",
  sir: "Excuse me, sir, can you help me?", sixteen: "My cousin is sixteen years old.", sixty: "The bus ride takes sixty minutes.",
  size: "What size shoes do you wear?", skirt: "She wears a blue skirt.", smart: "My sister is very smart.",
  smell: "This flower has a sweet smell.", snack: "I have a snack after school.", snake: "The snake moved quietly through the grass.",
  snow: "It started to snow this morning.", so: "I was tired, so I went to bed.", soccer: "We play soccer after school.",
  socks: "I wear warm socks in winter.", some: "I want some water, please.", soon: "The bus will arrive soon.",
  sound: "I heard a strange sound.", speak: "Can you speak English?", sports: "I like watching sports on TV.",
  spring: "Flowers bloom in spring.", station: "We waited at the train station.", stay: "I will stay home today.",
  steak: "My dad cooked steak for dinner.", still: "It is still raining outside.", stop: "Please stop at the red light.",
  street: "We walked down the street.", strong: "My dad is very strong.", sugar: "I don't want sugar in my tea.",
  summer: "We swim a lot in summer.", sunny: "It is a sunny day.", sure: "Are you sure about that?",
  sweet: "This cake is very sweet.", swim: "I like to swim in the pool.", tape: "Use tape to fix the paper.",
  television: "We watch television after dinner.", thirsty: "I am thirsty after running.",
  thirteen: "My sister is thirteen years old.", thirty: "The movie is thirty minutes long.", this: "This is my new bag.",
  tomorrow: "We have a test tomorrow.", tv: "I watch TV after dinner.", twelve: "There are twelve months in a year.",
  twenty: "There are twenty students in my class.", use: "You can use my pencil.", vacation: "We went to the beach on vacation.",
  vegetable: "I eat a vegetable with every meal.", visit: "We will visit my grandma this weekend.",
  wall: "There is a picture on the wall.", warm: "It is warm today.", weekend: "I play soccer on the weekend.",
  wet: "My shoes are wet from the rain.", which: "Which color do you like best?", wind: "The wind is very strong today.",
  window: "Please open the window.", winter: "It snows a lot in winter.", wonderful: "We had a wonderful trip.",
  worry: "Don't worry, everything will be fine.", writer: "She wants to be a writer.", wrong: "I chose the wrong answer.",
  young: "My little brother is very young.",

  // ===== Lv5 (193) =====
  "a few": "I have a few apples left.", "a little": "I want a little more rice.", "a lot": "I have a lot of homework today.",
  afraid: "I am afraid of the dark.", again: "Let's play this game again.", all: "All my friends came to the party.",
  always: "She always helps her friends.", answer: "Do you know the answer?", anybody: "Is anybody home?",
  anyone: "Does anyone want more juice?", anything: "I didn't eat anything for breakfast.", away: "The bird flew away.",
  back: "I will be back soon.", bake: "We bake cookies on Sundays.", basket: "Put the apples in the basket.",
  become: "I want to become a teacher.", before: "Wash your hands before dinner.", begin: "The class will begin soon.",
  blue: "The sky is blue today.", both: "I like both apples and bananas.", butter: "Spread butter on the bread.",
  careful: "Be careful on the stairs.", catch: "Can you catch the ball?", chicken: "We had chicken for dinner.",
  class: "My class has thirty students.", cloudy: "It is cloudy today.", cook: "My mom likes to cook.",
  cut: "Please cut the paper carefully.", daughter: "She is their only daughter.", delicious: "This soup is delicious.",
  did: "Did you finish your homework?", driver: "My uncle is a bus driver.", each: "Each student gets a book.",
  early: "I wake up early every day.", easy: "This math problem is easy.", enjoy: "I enjoy playing basketball.",
  enough: "We have enough food for everyone.", everybody: "Everybody is here now.", everyone: "Everyone likes the new teacher.",
  everything: "Everything is ready for the trip.", face: "Wash your face before bed.", farm: "My grandpa has a small farm.",
  fast: "The rabbit ran very fast.", fire: "We sat around the fire.", first: "She was the first to finish.",
  fish: "We caught a fish in the lake.", forget: "Don't forget your umbrella.", fork: "Please pass me a fork.",
  friday: "We have a test on Friday.", frisbee: "We played frisbee at the park.", garden: "My mom grows flowers in the garden.",
  get: "I get up at seven every day.", glad: "I am glad you are here.", goat: "The goat ate the grass.",
  gym: "We exercise in the gym.", hard: "This question is very hard.", hate: "I hate being late for school.",
  hear: "Can you hear the birds singing?", high: "The mountain is very high.", him: "I gave him my pencil.",
  hop: "The rabbit began to hop.", hope: "I hope it doesn't rain tomorrow.", hotel: "We stayed at a nice hotel.",
  housewife: "My aunt is a busy housewife.", hundred: "There are one hundred students in our grade.",
  hurry: "Hurry, or we will be late!", husband: "Her husband works at a hospital.", large: "The elephant is very large.",
  last: "This is the last question.", left: "Turn left at the corner.", lesson: "Our English lesson starts at nine.",
  lucky: "I feel very lucky today.", many: "I have many friends at school.", marker: "I drew a picture with a marker.",
  me: "Can you help me, please?", meet: "Let's meet at the library.", mom: "My mom makes great pancakes.",
  mommy: "Mommy, can I have a cookie?", monday: "We have art class on Monday.", monkey: "The monkey climbed the tree.",
  more: "May I have more rice, please?", mother: "My mother works at a hospital.", motorcycle: "My uncle rides a motorcycle.",
  mountain: "We hiked up the mountain.", mouth: "Open your mouth wide.", much: "I don't have much time.",
  music: "I love listening to music.", near: "The park is near my house.", night: "I read a book every night.",
  noon: "We eat lunch at noon.", number: "What is your phone number?", nurse: "My aunt is a kind nurse.",
  often: "I often walk to school.", once: "I visit my aunt once a month.", only: "She is the only girl in her class.",
  open: "Please open the door.", orange: "I ate a sweet orange.", order: "Can I order a pizza?",
  other: "I have two other pencils.", outside: "We play outside after school.", over: "The game is over now.",
  pants: "He wears black pants.", parent: "Each parent came to the school event.", party: "We had a birthday party.",
  pass: "Please pass the salt.", past: "The bus just went past our house.", people: "Many people came to the festival.",
  person: "She is a very kind person.", photo: "We took a photo at the park.", pick: "I will pick you up after school.",
  pin: "She wore a pretty pin on her jacket.", pizza: "We ordered pizza for dinner.", place: "This park is a nice place to play.",
  plan: "What is your plan for today?", pool: "We swim in the pool every summer.", practice: "I practice piano every day.",
  pray: "We pray before dinner.", prepare: "I prepare my bag the night before.", present: "This is a present for you.",
  price: "The price of the toy is low.", problem: "I have a math problem to solve.", pull: "Please pull the door open.",
  puppy: "Our new puppy is very playful.", purple: "She wears a purple dress.", push: "Push the door to open it.",
  queen: "The queen lives in a castle.", question: "I have a question for you.", quick: "That was a quick answer.",
  rabbit: "The rabbit hopped across the yard.", radio: "My dad listens to the radio in the car.",
  rain: "The rain stopped in the afternoon.", rainy: "It is a rainy day.", remember: "I remember my first day of school.",
  repeat: "Can you repeat that, please?", ride: "I ride my bike to school.", right: "Turn right at the next corner.",
  robot: "My little brother loves his toy robot.", rope: "We used a rope to climb the tree.", row: "We sat in the first row.",
  safe: "Wear a helmet to stay safe.", saturday: "We visit grandma every Saturday.", scared: "I was scared of the thunder.",
  second: "Wait a second, please.", seed: "We planted a seed in the garden.", seldom: "I seldom eat fast food.",
  "senior high school": "My sister goes to senior high school.", several: "I have several books to read.",
  shark: "We saw a shark at the aquarium.", shoe: "This shoe is too small.", shoes: "I need new shoes for school.",
  shout: "Please don't shout in the library.", skate: "We skate at the park on weekends.", smile: "She always has a big smile.",
  snowman: "We built a snowman in the yard.", sometimes: "I sometimes walk to school.", sorry: "I am sorry I was late.",
  spoon: "Please give me a spoon.", stamp: "I collect stamps from other countries.", sunday: "We go to the park on Sunday.",
  surf: "We tried to surf at the beach.", taiwan: "I was born in Taiwan.", taxi: "We took a taxi to the airport.",
  teach: "My mom teaches math at school.", tell: "Can you tell me a story?", tennis: "We play tennis on weekends.",
  test: "I studied hard for the test.", the: "The sun is shining today.", them: "I gave them my old toys.",
  third: "This is the third question.", thursday: "We have music class on Thursday.", ticket: "I bought a ticket for the movie.",
  tiger: "The tiger is a strong animal.", to: "I go to school by bus.", tonight: "We will watch a movie tonight.",
  town: "My grandma lives in a small town.", tuesday: "We have PE class on Tuesday.", understand: "I understand this lesson now.",
  unhappy: "She looked unhappy after the game.", us: "Please help us with our homework.", usually: "I usually walk to school.",
  waiter: "The waiter brought us the menu.", waitress: "The waitress was very friendly.", was: "It was a fun day.",
  watch: "I watch cartoons on Saturday morning.", wednesday: "We have art class on Wednesday.", welcome: "Welcome to our school!",
  well: "She sings very well.", were: "We were at the park yesterday.", wife: "His wife is a doctor.",
  win: "I hope our team will win.", windy: "It is very windy today.", yard: "We play in the yard after school.",
  your: "Is this your bag?",

  // ===== Lv6 (243) =====
  age: "What is your age?", agree: "I agree with your idea.", airplane: "We flew on an airplane to Japan.",
  airport: "We waited at the airport for our flight.", also: "I also like drawing.", angry: "My mom was angry when I was late.",
  another: "Can I have another cookie?", apartment: "We live in a small apartment.", april: "My birthday is in April.",
  artist: "She wants to be an artist.", august: "School starts again in August.", bakery: "We bought bread at the bakery.",
  baseball: "My brother plays baseball every weekend.", basketball: "We played basketball after school.",
  bath: "I take a bath every night.", bathroom: "The bathroom is upstairs.", beach: "We swam at the beach.",
  beautiful: "The sunset was beautiful.", because: "I stayed home because I was sick.", bedroom: "My bedroom is on the second floor.",
  believe: "I believe you can do it.", between: "The park is between two schools.", blanket: "I sleep with a warm blanket.",
  blow: "The wind began to blow hard.", boat: "We rode a boat across the lake.", borrow: "Can I borrow your pencil?",
  boss: "My mom's boss is very kind.", bottle: "Please fill my water bottle.", bottom: "The toy fell to the bottom of the box.",
  bun: "I ate a sweet bun for breakfast.", camera: "My dad bought a new camera.", camp: "We went to summer camp last year.",
  care: "Take care of your little sister.", cent: "The candy costs fifty cents.", chance: "Give me a chance to try again.",
  cheap: "This toy is very cheap.", cheese: "I like cheese on my sandwich.", china: "My grandma was born in China.",
  chocolate: "I love chocolate ice cream.", christmas: "We decorate a tree at Christmas.", church: "We go to church on Sunday.",
  clap: "Everyone began to clap.", clean: "Please clean your room.", clerk: "The clerk helped me find the book.",
  climb: "We like to climb trees.", club: "I joined the art club.", cold: "It is very cold today.",
  comb: "Use a comb to fix your hair.", comfortable: "This chair is very comfortable.", convenient: "The bus stop is very convenient.",
  corner: "The store is on the corner.", cost: "How much does this cost?", couch: "We watched TV on the couch.",
  count: "Can you count to one hundred?", cousin: "My cousin visits us every summer.", crazy: "That was a crazy idea.",
  dead: "The plant looks dead.", deaf: "My grandpa is a little deaf.", deal: "It's not a big deal.",
  december: "We have winter break in December.", decide: "I can't decide which one to choose.",
  "department store": "We bought new shoes at the department store.", dictionary: "Use a dictionary to check the spelling.",
  different: "Our shoes are different colors.", doctor: "My aunt is a doctor.", "dodge ball": "We played dodge ball in gym class.",
  dodgeball: "We played dodgeball in gym class.", dot: "Connect the dots to make a picture.",
  dragon: "The dragon danced in the parade.", drawer: "I keep my socks in the drawer.", drum: "My brother plays the drum.",
  during: "We were quiet during the movie.", "e-mail": "I sent an e-mail to my teacher.",
  earth: "The earth moves around the sun.", east: "The sun rises in the east.", easter: "We paint eggs at Easter.",
  either: "You can choose either one.", "elementary school": "I study at an elementary school.",
  else: "Does anyone else want juice?", email: "I sent an email to my teacher.", end: "We were sad at the end of the trip.",
  enter: "Please enter the classroom quietly.", eve: "We stayed up late on New Year's Eve.",
  example: "Can you give me an example?", fact: "Here is an interesting fact about whales.",
  factory: "My uncle works at a factory.", famous: "She is a famous singer.", far: "The school is not far from my house.",
  farmer: "The farmer grows rice and vegetables.", favorite: "Pizza is my favorite food.", february: "My birthday is in February.",
  few: "Only a few students were late.", fight: "The brothers had a small fight.", fill: "Please fill the cup with water.",
  finally: "We finally arrived home.", finger: "I hurt my finger.", finish: "I will finish my homework soon.",
  fisherman: "The fisherman caught a big fish.", fix: "My dad can fix the bike.", floor: "The toy fell on the floor.",
  follow: "Please follow me to the classroom.", front: "Wait for me in front of the school.", fun: "We had so much fun today.",
  garbage: "Please take out the garbage.", gate: "We waited at the school gate.", gift: "Thank you for the birthday gift.",
  glass: "Please give me a glass of water.", glove: "I wear gloves in winter.", goose: "A goose is bigger than a duck.",
  grape: "I ate a bunch of grapes.", guava: "Guava is my favorite fruit.", guitar: "My sister is learning to play the guitar.",
  habit: "Brushing your teeth is a good habit.", hamburger: "We ate hamburgers for lunch.", happen: "What happened at school today?",
  health: "Exercise is good for your health.", heart: "My heart beats fast when I run.", heavy: "This box is very heavy.",
  helpful: "My classmate is very helpful.", her: "This is her book.", hide: "Let's play hide and seek.",
  hike: "We went on a hike last weekend.", his: "This is his bike.", history: "I like learning about history.",
  hobby: "My hobby is drawing.", holiday: "We visited grandma during the holiday.", hospital: "My mom works at the hospital.",
  idea: "That is a great idea.", important: "Sleep is important for your health.", insect: "A ladybug is a small insect.",
  inside: "Let's go inside, it's cold.", jacket: "Wear your jacket, it's chilly.", january: "We start a new year in January.",
  july: "We have summer vacation in July.", june: "School ends in June.", kangaroo: "A kangaroo can jump very high.",
  knife: "Be careful with the knife.", know: "I know the answer.", koala: "A koala sleeps most of the day.",
  late: "I was late for school today.", lazy: "Don't be lazy, finish your homework.", lemon: "This drink tastes like lemon.",
  let: "Let me help you with that.", library: "We borrowed books from the library.", like: "I like reading books.",
  lip: "She has a cut on her lip.", listen: "Please listen to the teacher.", little: "The little dog is very cute.",
  live: "We live near the school.", "living room": "We watch TV in the living room.", loud: "The music was too loud.",
  lovely: "What a lovely day!", low: "The plane flew low over the field.", "mail carrier": "The mail carrier brings letters every day.",
  mailman: "The mailman brings letters every day.", map: "Use the map to find the way.", march: "Spring begins in March.",
  market: "We buy vegetables at the market.", math: "Math is my favorite subject.", mathematics: "Mathematics can be fun.",
  may: "It may rain tomorrow.", maybe: "Maybe we can go tomorrow.", meeting: "My mom has a meeting at work.",
  minute: "Wait one minute, please.", month: "My birthday is next month.", most: "Most students like recess.",
  mrt: "We took the MRT to the museum.", museum: "We visited the art museum.", must: "You must wear a helmet.",
  my: "This is my school bag.", nail: "I hurt my nail.", necktie: "My dad wears a necktie to work.",
  noodle: "I love eating noodle soup.", north: "We drove north to the mountains.", november: "It gets cold in November.",
  october: "We celebrate a festival in October.", oil: "Add a little oil to the pan.", our: "This is our classroom.",
  ox: "The ox pulled the cart.", papaya: "Papaya is sweet and orange.", peach: "I ate a juicy peach.",
  pear: "This pear is very sweet.", piano: "She practices piano every day.", plane: "We took a plane to Japan.",
  plate: "Please put the food on the plate.", pocket: "I keep my keys in my pocket.", pond: "There are fish in the pond.",
  popcorn: "We ate popcorn at the movies.", "post office": "I mailed the letter at the post office.",
  postcard: "I sent a postcard from my trip.", put: "Please put your shoes here.", quiet: "Please be quiet in the library.",
  rat: "A rat ran across the yard.", ready: "Are you ready for school?", restroom: "Where is the nearest restroom?",
  "roller skate": "I got new roller skates for my birthday.", rose: "She gave me a red rose.", round: "The ball is round.",
  sale: "The toy store is having a sale.", science: "We did an experiment in science class.", sell: "The shop sells fresh fruit.",
  september: "School starts again in September.", shake: "Let's shake hands.", shape: "What shape is this box?",
  share: "Please share your toys with your sister.", shopkeeper: "The shopkeeper was very friendly.",
  shorts: "I wear shorts in summer.", sick: "I stayed home because I was sick.", side: "Walk on the right side of the road.",
  snowy: "It was a snowy morning.", south: "We drove south to the beach.", space: "Astronauts travel into space.",
  special: "Today is a special day.", spider: "A spider made a web in the garden.", story: "My grandma tells great stories.",
  strawberry: "I love strawberry ice cream.", sweater: "Wear a sweater, it's cold outside.",
  "t-shirt": "I wear a T-shirt in summer.", tail: "The dog wagged its tail.", their: "This is their house.",
  thick: "The book is very thick.", thin: "The paper is very thin.", thing: "What is that thing on the table?",
  tie: "My dad wears a tie to work.", tired: "I am tired after playing all day.", toast: "I eat toast for breakfast.",
  tomato: "I put tomato in my salad.", tooth: "I lost a tooth yesterday.", trash: "Please throw the trash away.",
  turkey: "We ate turkey on Thanksgiving.", turtle: "The turtle moved very slowly.", umbrella: "Bring your umbrella, it might rain.",
  useful: "This tool is very useful.", vest: "He wears a vest over his shirt.", video: "We watched a funny video.",
  voice: "She has a beautiful singing voice.", wallet: "My dad keeps his money in his wallet.",
  weak: "I felt weak after being sick.", west: "The sun sets in the west.", will: "I will finish my homework soon.",
  wish: "I wish you a happy birthday.", workbook: "Please open your workbook to page five.", would: "Would you like some tea?",
};

// ===== Lv7 (575, wL7 — 國中一年級單字練習題用) =====
Object.assign(SENTENCES, {
  absent: "He was absent from school today.", accept: "I accept your apology.", accident: "She had a small accident on her bike.",
  across: "The store is across the street.", action: "The movie has a lot of action.", active: "My grandma is still very active.",
  activity: "Our club had a fun activity today.", actor: "He wants to become an actor.", actress: "She is my favorite actress.",
  adjective: "\"Happy\" is an adjective.", adult: "Only adults can enter this room.", adventure: "We went on an exciting adventure.",
  adverb: "\"Quickly\" is an adverb.", advice: "She gave me good advice.", advise: "I advise you to study harder.",
  against: "He leaned against the wall.", ahead: "Look ahead before you cross the street.", aim: "My aim is to finish the project early.",
  "air conditioner": "Please turn on the air conditioner.", airline: "This airline flies to many countries.", airmail: "I sent the letter by airmail.",
  alike: "The twins look alike.", alive: "The old tree is still alive.", alley: "We walked down a narrow alley.",
  allow: "My parents allow me to stay up late on weekends.", almost: "I almost missed the bus.", although: "Although it rained, we still played outside.",
  altogether: "The trip cost five hundred dollars altogether.", ambulance: "The ambulance arrived quickly.", among: "She was popular among her classmates.",
  anger: "He tried to control his anger.", ankle: "I hurt my ankle while running.", anyway: "It's late, but let's go anyway.",
  apologize: "I apologized for being late.", area: "This area is very quiet.", argue: "The brothers often argue over small things.",
  army: "His father served in the army.", around: "We walked around the park.", arrange: "Let's arrange a time to meet.",
  article: "I read an interesting article today.", asian: "She studies Asian history.", assistant: "The teacher's assistant helped us.",
  attack: "The team planned their attack.", attention: "Please pay attention in class.", australian: "My friend is Australian.",
  avoid: "We should avoid junk food.", backward: "He walked backward by accident.", badminton: "We play badminton every weekend.",
  balcony: "We have a small balcony at home.", band: "He plays drums in a band.", banker: "Her father is a banker.",
  bar: "There is a snack bar near school.", barbecue: "We had a barbecue in the yard.", base: "The team returned to their base.",
  basement: "We keep old boxes in the basement.", basic: "This is a basic math question.", bat: "A bat flew out of the cave.",
  bear: "We saw a bear at the zoo.", beat: "Our team beat the other team.", been: "I have been to Japan before.",
  beer: "My uncle drinks beer sometimes.", behave: "Please behave in the library.", behind: "The cat hid behind the sofa.",
  bell: "The school bell rang.", belt: "He wears a black belt.", bench: "We sat on a bench in the park.",
  beside: "She sat beside her best friend.", besides: "Besides English, I also study Japanese.", bill: "My dad paid the electricity bill.",
  bite: "The dog gave a gentle bite.", blackboard: "The teacher wrote on the blackboard.", block: "There is a bakery two blocks away.",
  blood: "The doctor checked his blood pressure.", bored: "I felt bored during the long class.", boring: "That movie was really boring.",
  born: "She was born in Taipei.", "both xxx and": "She is both smart and kind.", bother: "Sorry to bother you.",
  bow: "The actors took a bow.", bowl: "Please pass me a bowl of rice.", bowling: "We went bowling last weekend.",
  boyfriend: "She talked about her boyfriend.", brain: "The brain controls our whole body.", branch: "A bird landed on the branch.",
  brick: "The house is made of brick.", bring: "Please bring your umbrella tomorrow.", britain: "Britain has a long history.",
  british: "She has a British accent.", bucket: "He filled the bucket with water.", buffet: "We ate at a buffet restaurant.",
  bug: "There is a bug on the leaf.", build: "They plan to build a new library.", business: "My aunt runs a small business.", cabinet: "The cups are in the cabinet.",
  cable: "The TV cable is broken.", cafeteria: "We eat lunch in the cafeteria.", cage: "The bird lives in a cage.",
  campus: "The school campus is very big.", can: "Can you help me, please?", canadian: "My pen pal is Canadian.",
  cancel: "We had to cancel the trip.", candle: "She blew out the candles.", captain: "He is the captain of our team.",
  carry: "Can you carry this bag for me?", cash: "I paid in cash.", cassette: "My dad still has old cassette tapes.",
  castle: "We visited an old castle.", cause: "What was the cause of the fire?", ceiling: "There is a lamp on the ceiling.",
  center: "The mall is in the center of town.", certainly: "I will certainly help you.", channel: "Let's change the channel.",
  chapter: "This chapter is about ancient history.", character: "My favorite character is the hero.", chart: "The chart shows our test scores.",
  cheat: "You must not cheat on the test.", check: "Please check your answers.", cheerleader: "She is a cheerleader for the team.",
  chess: "We played chess after school.", childhood: "I had a happy childhood.", choice: "You have two choices.",
  chopsticks: "We eat noodles with chopsticks.", clear: "The instructions were very clear.", clothes: "Please fold your clothes.",
  clothing: "The store sells winter clothing.", coach: "Our coach is very strict.", coast: "We drove along the coast.",
  cockroach: "There was a cockroach in the kitchen.", collect: "I collect stamps from other countries.", collection: "He has a big coin collection.",
  college: "My sister goes to college now.", comfortably: "The cat slept comfortably on the sofa.", comic: "He reads comic books every night.",
  comment: "She left a kind comment.", company: "My dad works for a big company.", compare: "Let's compare our two answers.",
  complete: "Please complete the form.", congratulation: "Congratulations on your new job!", "contact lens": "She wears contact lenses.",
  continue: "Let's continue the story tomorrow.", control: "He lost control of the bike.", conversation: "We had a long conversation.",
  cotton: "This shirt is made of cotton.", could: "Could you help me, please?", country: "Which country do you want to visit?",
  countryside: "We spent the weekend in the countryside.", couple: "A couple was walking in the park.", course: "This course is about science.",
  create: "She likes to create new art.", "credit card": "He paid with a credit card.", crowd: "A big crowd gathered at the park.",
  customer: "The customer asked for a refund.", danger: "Swimming here can be a danger.", dangerous: "It is dangerous to run near the pool.",
  death: "The story is about life and death.", decision: "It was a hard decision to make.", decorate: "We decorated the classroom for the party.",
  deliver: "The mailman delivers letters every day.", dentist: "I visited the dentist yesterday.", department: "She works in the sales department.",
  depend: "It depends on the weather.", describe: "Can you describe your dog?", desert: "Camels live in the desert.",
  design: "She designed a new poster.", dial: "Please dial this number.", diamond: "The ring has a small diamond.",
  diet: "He is on a healthy diet.", difference: "What is the difference between these two?", diligent: "She is a diligent student.",
  direction: "We walked in the wrong direction.", disappear: "The magician made the coin disappear.", discover: "Scientists discovered a new species.",
  discuss: "Let's discuss the plan together.", distance: "The distance to school is short.", divide: "Please divide the cake into six pieces.",
  division: "We are learning division in math.", done: "I am done with my homework.", dozen: "I bought a dozen eggs.",
  dream: "I had a strange dream last night.", drop: "Be careful not to drop the plate.", dumb: "That was a dumb mistake.",
  earn: "She works hard to earn money.", eastern: "They live in the eastern part of the city.", elder: "Respect your elders.",
  enemy: "The two teams are not really enemies.", engineer: "My uncle is an engineer.", england: "London is the capital of England.",
  englishman: "He is an Englishman.", equal: "We should treat everyone equally.", especially: "I like fruit, especially apples.",
  europe: "They traveled around Europe.", european: "She studies European history.", event: "The school held a big event.",
  ever: "Have you ever been to Korea?", everywhere: "I looked everywhere for my keys.", excite: "The news will excite everyone.",
  excited: "I am excited about the trip.", exciting: "That was an exciting game.", excuse: "Excuse me, where is the library?",
  exercise: "Daily exercise keeps you healthy.", exercising: "She is exercising in the park.", "expensive fruit": "Mangoes can be an expensive fruit in winter.",
  explain: "Can you explain this question?", fail: "I hope I don't fail the test.", fair: "The rule should be fair to everyone.",
  fantastic: "We had a fantastic trip.", favor: "Can you do me a favor?", fear: "He has a fear of heights.",
  feather: "The bird lost a feather.", fence: "There is a fence around the garden.", field: "The players ran onto the field.",
  final: "This is the final question.", find: "I can't find my pencil case.", flat: "The road here is flat.",
  flight: "Our flight leaves at six.", flour: "We need more flour for the cake.", flute: "She plays the flute in the band.",
  fool: "Don't be a fool.", foolish: "It was foolish to forget my umbrella.", foot: "My foot hurts a little.",
  forward: "Let's move forward with the plan.", "french fries": "I ordered french fries and a burger.", friendship: "Their friendship lasted for years.",
  fries: "Can I have some fries?", frighten: "The loud noise frightened the cat.", full: "I am full after lunch.",
  future: "What do you want to do in the future?", game: "Let's play a game.", gather: "We gathered around the campfire.",
  gentle: "She has a gentle voice.", gentleman: "He is a real gentleman.", german: "She is learning German.",
  germany: "He studied in Germany last year.", ghost: "The movie was about a friendly ghost.", girlfriend: "He talked about his girlfriend.",
  glasses: "I need my glasses to read.", god: "Ancient people believed in many gods.", gram: "This recipe needs 100 grams of sugar.",
  grass: "The grass is green after the rain.", greedy: "Don't be greedy with your food.", greet: "We greet our teacher every morning.",
  grow: "This plant will grow tall.", guard: "A guard stood at the gate.", guess: "Can you guess my age?",
  guide: "The guide showed us around the museum.", gun: "The police officer carried a gun.", guy: "He is a nice guy.",
  halloween: "We wore costumes for Halloween.", hammer: "He used a hammer to fix the chair.", handkerchief: "She keeps a handkerchief in her bag.",
  handle: "Turn the handle to open the door.", handsome: "He looks very handsome today.", happy: "I am happy to see you.",
  "hard-working": "She is a hard-working student.", hardly: "I could hardly hear you.", healthy: "Eating vegetables keeps you healthy.",
  height: "What is your height?", helicopter: "A helicopter flew over the school.", hers: "This umbrella is hers.",
  highway: "We drove on the highway.", hold: "Can you hold my bag for a moment?", homesick: "She felt homesick on the first night.",
  honey: "I like honey on my toast.", horrible: "That was a horrible smell.", huge: "The elephant is huge.",
  human: "Humans need water to survive.", humid: "It is very humid in summer.", hunger: "The soup satisfied his hunger.",
  hunt: "Lions hunt in groups.", hunter: "The hunter followed the tracks.", illness: "He recovered quickly from his illness.",
  imagine: "Can you imagine living on the moon?", impossible: "Nothing is impossible if you try.", inch: "The fish was six inches long.",
  instrument: "What instrument do you play?", interest: "She has a strong interest in art.", interested: "I am interested in science.",
  interesting: "This book is very interesting.", introduce: "Let me introduce my friend.", invitation: "I received an invitation to the party.",
  iron: "Please iron my shirt.", island: "We visited a small island.", italy: "Pizza comes from Italy.",
  itself: "The cat cleaned itself.", jazz: "My dad likes to listen to jazz.", jeans: "He wears blue jeans.",
  joy: "Her smile is full of joy.", jump: "The rabbit can jump very high.", "junior high school": "I study at a junior high school.",
  just: "I just finished my homework.", keep: "Please keep this secret.", key: "I lost my house key.",
  kill: "The movie was about a detective solving a murder.", kilogram: "The bag weighs two kilograms.", knee: "He hurt his knee playing soccer.",
  knock: "Please knock before you enter.", korea: "My cousin lives in Korea.", korean: "She is learning Korean.",
  lake: "We had a picnic by the lake.", lamp: "Turn off the lamp before you sleep.", land: "The plane will land soon.",
  lane: "Stay in your lane while swimming.", lantern: "We made a paper lantern.", later: "I will call you later.",
  laugh: "The joke made everyone laugh.", lay: "She laid the book on the table.", leader: "He is a good team leader.",
  lend: "Can you lend me a pencil?", length: "What is the length of this rope?", letter: "I wrote a letter to my grandma.",
  lid: "Please close the lid tightly.", life: "City life can be very busy.", lift: "Can you lift this box?",
  lightning: "The lightning lit up the sky.", link: "Click this link for more information.", list: "I made a list of things to buy.",
  loaf: "We bought a loaf of bread.", look: "Look at that beautiful sunset.", lose: "I don't want to lose the game.",
  loser: "Nobody likes to be called a loser.", luggage: "Please check your luggage before boarding.", machine: "This machine washes the clothes.",
  magician: "The magician surprised the audience.", mail: "I checked the mail today.", main: "The main character is very brave.",
  male: "The male lion has a mane.", manager: "She is the manager of the store.", manner: "He speaks in a polite manner.",
  mask: "We wore masks at the party.", mat: "Please wipe your feet on the mat.", matter: "It doesn't matter to me.",
  meal: "We had a big meal together.", mean: "What does this word mean?", meaning: "I don't understand the meaning of this sentence.",
  meat: "He doesn't eat meat.", mechanic: "The mechanic fixed our car.", medicine: "Take this medicine after meals.",
  member: "She is a member of the art club.", memory: "I have a good memory for names.", menu: "Can I see the menu, please?",
  metal: "This spoon is made of metal.", might: "It might rain tomorrow.", mile: "The store is one mile away.",
  million: "The city has a million people.", mistake: "Everyone makes mistakes sometimes.", modern: "This is a modern building.",
  moment: "Wait a moment, please.", mouse: "A mouse ran across the floor.", movement: "The dance had smooth movements.",
  mud: "His shoes were covered in mud.", musician: "She wants to be a musician.", myself: "I made this cake myself.",
  narrow: "The path is very narrow.", natural: "It is natural to feel nervous before a test.", nature: "We learn about nature in this class.",
  naughty: "The naughty puppy chewed my shoe.", nearly: "It is nearly time for dinner.", needle: "She used a needle to sew the button.",
  neighbor: "My neighbor is very friendly.", neither: "Neither of us wanted to leave.", nephew: "My nephew is five years old.",
  nervous: "I feel nervous before the exam.", next: "What is the next question?", niece: "My niece loves to draw.",
  nobody: "Nobody was home.", nod: "She nodded to show she agreed.", noise: "There was a loud noise outside.",
  none: "None of the answers were correct.", northern: "They live in the northern part of the island.", notebook: "I write my ideas in a notebook.",
  nothing: "There is nothing in the box.", opinion: "What is your opinion about this?", ours: "This classroom is ours.",
  "over-weight": "Carrying too much can make your bag over-weight.", overpass: "We walked across the overpass.", owner: "The dog's owner called for it.",
  painful: "The injury looked painful.", pale: "She looked pale after the long trip.", park: "We played in the park.",
  partner: "Choose a partner for this activity.", passenger: "The bus was full of passengers.", path: "Follow this path to the garden.",
  patient: "The nurse cared for the patient.", pattern: "This shirt has a nice pattern.", pause: "Let's pause the video for a second.",
  pe: "We have PE class on Friday.", peace: "They finally made peace.", peaceful: "The village was quiet and peaceful.",
  perfect: "Your handwriting is perfect.", period: "This period in history is fascinating.", philippines: "My friend is from the Philippines.",
  photographer: "The photographer took our picture.", "physical education": "Physical education helps us stay fit.", pile: "There was a pile of books on the desk.",
  pipe: "Water flows through this pipe.", plain: "She likes plain rice, not fried rice.", playground: "The kids played at the playground.",
  pleasant: "It was a pleasant afternoon.", pleased: "I am pleased with my test score.", poem: "She wrote a short poem.",
  popular: "This song is very popular.", possible: "Is it possible to finish today?", post: "She will post the letter tomorrow.",
  pound: "The bag weighs about a pound.", power: "The storm cut off the power.", praise: "The teacher praised her hard work.",
  prefer: "I prefer tea to coffee.", primary: "My little brother is in primary school.", prince: "The prince lived in a big castle.",
  princess: "The princess wore a beautiful dress.", principal: "The principal spoke at the assembly.", prize: "She won first prize in the contest.",
  project: "Our group project is due next week.", promise: "I promise to help you.", protect: "We should protect the environment.",
  pump: "He used a pump to fill the tire.", quit: "He decided to quit the team.", railroad: "The railroad runs through the town.",
  railway: "We took the railway to the city.", rainbow: "We saw a rainbow after the rain.", raise: "Please raise your hand to answer.",
  rare: "This kind of bird is very rare.", rather: "I would rather stay home today.", reach: "Can you reach the top shelf?",
  reason: "What is the reason for being late?", record: "He set a new school record.", recorder: "We play the recorder in music class.",
  recycle: "We recycle bottles and paper at school.", refrigerator: "Put the milk in the refrigerator.", regular: "This is my regular seat.",
  remind: "Please remind me to call mom.", rent: "They rent a small apartment.", reporter: "The reporter asked many questions.",
  "republic of china": "Taiwan is also called the Republic of China.", result: "The result of the test was good.", revise: "I need to revise my essay.",
  rise: "The sun will rise soon.", river: "We fished in the river.", rob: "Someone tried to rob the store.",
  rock: "He climbed onto a big rock.", rome: "Rome is the capital of Italy.", root: "The tree has deep roots.",
  russia: "Russia is a very large country.", russian: "She is learning Russian.", safety: "Wear a helmet for your safety.",
  sail: "We watched the boats sail by.", sailing: "They enjoy sailing on weekends.", sailor: "The sailor worked on a big ship.",
  salesman: "The salesman was very friendly.", sample: "Try this free sample.", "san francisco": "She was born in San Francisco.",
  saucer: "The cup sat on a small saucer.", scientist: "She wants to be a scientist.", screen: "The movie screen was very big.",
  search: "We searched for the missing keys.", seat: "Please take your seat.", secretary: "The secretary answered the phone.",
  seesaw: "The kids played on the seesaw.", select: "Please select the correct answer.", selfish: "It was selfish of him not to share.",
  semester: "The new semester starts in September.", sense: "It doesn't make sense to me.", serve: "The waiter will serve our food soon.",
  service: "The restaurant has great service.", sharp: "Be careful, the knife is sharp.", shoot: "He tried to shoot the ball into the basket.",
  shop: "She works at a small shop.", shore: "We walked along the shore.", shot: "It was a great shot.",
  should: "You should drink more water.", shoulder: "He carried the bag on his shoulder.", show: "Let me show you my drawing.",
  sidewalk: "We walked on the sidewalk.", sight: "The mountain view was a beautiful sight.", silence: "There was silence in the room.",
  silent: "Please be silent during the test.", simple: "The recipe is very simple.", simply: "I simply forgot the time.",
  since: "I have known her since childhood.", singapore: "We flew to Singapore for vacation.", single: "She lives alone in a single room.",
  skinny: "The kitten looked very skinny.", slender: "She has slender fingers.", slim: "He wants to look more slim and fit.",
  soldier: "The soldier stood at attention.", solve: "Can you solve this puzzle?", somebody: "Somebody left their bag here.",
  someone: "Someone called for you earlier.", something: "I want to tell you something.", somewhere: "Let's go somewhere new this weekend.",
  sort: "What sort of music do you like?", southern: "They live in the southern part of the country.", spend: "I spend an hour on homework every day.",
  stage: "She sang on the stage.", state: "Which state did you visit?", steal: "He would never steal anything.",
  steam: "Steam rose from the hot soup.", stingy: "He is too stingy to share his snacks.", strange: "That was a strange dream.",
  stream: "A small stream ran through the forest.", stupid: "That was a stupid mistake.", style: "I like your new hair style.",
  such: "I have never seen such a big dog.", sudden: "It was a sudden change of plan.", suddenly: "Suddenly, the lights went out.",
  suit: "He wore a black suit.", surprised: "I was surprised by the news.", swing: "The kids played on the swing.",
  tableware: "We washed all the tableware.", talkative: "My little sister is very talkative.", team: "Our team won the game.",
  teenager: "She is a teenager now.", term: "This term, we have five subjects.", terrible: "The weather was terrible today.",
  terrific: "That was a terrific idea.", than: "She is taller than me.", thanksgiving: "We celebrate Thanksgiving in November.",
  "thanksgiving day": "Thanksgiving Day is a time for family.", theirs: "That car is theirs.", thief: "The thief ran away quickly.",
  think: "What do you think about this plan?", though: "It was fun, though a bit tiring.", thousand: "The stadium holds a thousand people.",
  through: "We walked through the park.", throw: "Can you throw the ball to me?", time: "What time is it now?",
  tip: "She gave the waiter a tip.", title: "What is the title of this book?", top: "He climbed to the top of the hill.",
  topic: "Let's discuss a new topic today.", total: "The total cost was fifty dollars.", tour: "We took a tour of the museum.",
  tourist: "Many tourists visit this beach.", toward: "We walked toward the school gate.", towel: "Please bring your own towel.",
  track: "The runners lined up on the track.", traffic: "There was heavy traffic this morning.", treasure: "They found hidden treasure.",
  treat: "Let me treat you to lunch.", trick: "He played a fun trick on his brother.", trouble: "I don't want to get into trouble.",
  trust: "You can trust me with your secret.", truth: "Please tell me the truth.", tunnel: "The train went through a tunnel.",
  twice: "I have visited Japan twice.", type: "What type of music do you like?", typewriter: "My grandpa still has an old typewriter.",
  typhoon: "School was closed because of the typhoon.", "under-weight": "The doctor said the puppy was under-weight.", underpass: "We walked through the underpass.",
  unit: "This chapter has five units.", until: "We waited until the rain stopped.", valley: "The village sits in a green valley.",
  verb: "\"Run\" is a verb.", victory: "The team celebrated their victory.", vinegar: "Add a little vinegar to the salad.",
  violin: "She practices the violin every day.", vocabulary: "We learn new vocabulary every week.", wake: "I wake up at six every morning.",
  war: "The museum has exhibits about the war.", waste: "Don't waste your food.", way: "This is the way to the station.",
  wedding: "We attended their wedding last month.", western: "They live in the western part of the city.", whatever: "You can choose whatever you like.",
  while: "While I was reading, the phone rang.", whole: "I ate the whole apple.", wild: "The wild animals live in the forest.",
  wine: "My parents had a glass of wine.", without: "I can't live without my phone.", world: "She wants to travel around the world.",
  yet: "I haven't finished my homework yet.", yours: "Is this pencil yours?", yourself: "Take care of yourself.",
  zebra: "We saw a zebra at the zoo.",
});

if (typeof module !== "undefined" && module.exports) module.exports = { SENTENCES };
